
// =======================
// DESKRIPSI B
// =======================

const descEpisodeSynopsis = {
	"01" : "Di kesempatan kali ini, para member Gen-3 dan Gen-4 menantang dirinya bermain drama komedi dengan live! Benar-benar pengalaman pertama bagi mereka~! Ditambah dengan live perform mereka juga after talk bareng Saraba Seishun no Hikari!",
	"02" : "Rilisan khusus untuk supporter kali ini adalah Nogizaka Under Live 2021! Ya, seperti yang sudah kita tahu bahwa Under Live ini adalah penampilan terakhir dari Watanabe Miria & Ito Junna sebagai bagian dari member Nogizaka46. Berbeda dengan under live sebelumnya, kali ini diadakan tanpa kehadiran para penonton.",
	"03" : "Setelah tahun kemarin tidak dilaksakannya @JAM EXPO karena pandemi, akhirnya tahun ini kembali diadakan. Sama seperti 2 tahun sebelumnya, mereka salah satunya menghadirkan perform dari Nogizaka46 gen-4.",
	"04" : "Rilisan khusus untuk supporter kali ini adalah Nogizaka 28th SG Underlive 2021! Ya, seperti yang sudah kita tahu bahwa Underlive ini adalah penampilan terakhir dari Terada Ranze sebagai bagian dari member Nogizaka46. Berbeda dengan under live sebelumnya, kali ini dihadiri para penonton meskipun menerapkan protokol kesehatan pencegahan Corona.",
	"05" : "Dalam memperingati rilis single ke-28 Nogizaka46 \"Kimi ni Shikarareta\" dan sebagai pengganti event handshake nasional yang tidak dapat diadakan karena penyebaran virus corona, diadakan Minilive yang membawakan beberapa lagu dari single ini.",
	"06" : "Dalam Omitatekai kedua Gen-5 ini merupakan penampilan keseluruhan member yaitu 11 orang. Alasan dibuatnya Omitatekai kedua karena pada Omitatekai sebelumnya sebanyak 4 orang tidak dapat berpartisipasi. Seperti biasa dalam tradisi omitatekai, para member akan memperkenalkan dirinya, menunjukkan keahlian mereka (disini hanya 4 orang saja), dan melakukan mini live.",
	"07" : "Memperingati ulang tahunnya yang ke-10, Nogizaka46 mengadakan acara tahunannya yaitu 10th Birthday Live di Nissan Stadium selama 2 hari. Dalam 2 hari tersebut mereka menyanyikan serangkaian lagu-lagu dari single pertama hingga single terakhir ke-29. Yang mengejutkannya adalah kehadiran para OG (Old Girl) atau para lulusan. Hari pertama kita diberikan penampilan Ikoma Rina dan Ito Marika. Dan di hari ke-2 yang kami kerjakan ini adalah 5 orang lulusan, yaitu antara lain Nishino Nanase, Shiraishi Mai, Ikuta Erika, Takayama Kazumi dan Matsumura Sayuri.",
	"08" : "Setelah diselenggarakan juga acara yang sama pada single sebelumnya, Nogizaka46 kembali memperingati rilis single ke-29 Nogizaka46 \"Actually.. \" ini dengan Mini live secara streaming. Para member membawakan semua lagu dari single ini (kecuali lagu solo Kitano Hinako) termasuk performance pertama kalinya dari lagu \"Fukayomi\" dengan center Saito Asuka dan \"Suki ni natte mita\" dengan center Yamashita Mizuki. Juga disini yang ditunggu-tunggu datang juga, mereka memperlihatkan uniform terbarunya.",
	"09" : "Seperti yang kita ketahui kalau member yang begitu energik ini mengumumkan kelulusannya akhir Januari lalu. Dan Kiichan meskipun sudah masuk senbatsu 9x namun ia lebih memilih konsernya bersama member Under. Konser ini diadakan di PIA Arena MM Yokohama pada tanggal 24 Maret 2022, sehari sebelum konser 29th SG Under Live dilaksanakan. Setlist, pemilihan member unit semua dipilih sesuai keinginan Kiichan.",
	"10" : "Dalam event besar Tokyo Idol Festival 2022, salah satu grup Sakamichi yaitu Nogizaka46 gen-5 berkesempatan untuk pertama kalinya tampil disini. Mereka membawakan 6 buah lagu, termasuk 2 lagu gen-5 yaitu \"Zetsubou no Ichibyou mae\" dan \"Bandaid Hagasu you na Wakarekata\"",
	"11" : "Nogizaka46 1st YEAR BIRTHDAY LIVE adalah konser Nogizaka46 yang diadakan pada tanggal 22 Februari 2013 dalam rangka merayakan ulang tahun mereka yang ke satu tahun. Konsernya diadakan di Makuhari Messe Chiba, yang pada saat itu adalah venue terbesar yang mereka kunjungi selama tur. Pada hari itu, mereka membawakan total 27 lagu, termasuk 24 lagu dari single debutnya 'Guru Curtain' pada bulan Februari 2012 hingga single 'Seifuku no Mannequin', dan lagu baru 'Kimi no Na wa Kibou' beserta couplingnya yang akan dirilis sebagai bagian dari single ke-5.",
	"12" : "Karena MoeFang sudah ngesub konser grad-nya member, kini kami kembali ngesub konser kelulusannya Higuchi Hina, beberapa hari setelah Underlive dimana Maaya, sahabatnya juga disana stage terakhirnya di Nogizaka46. Dengan judul Ceremony, sudah pasti banyak ngobrolnya, jadi kita bisa mendengarkan kenangan para member kepada Chima.",
	"13" : "Setelah diselenggarakan juga acara yang sama pada single sebelumnya, Nogizaka46 kembali memperingati rilis single ke-30 Nogizaka46 \"Suki to Iu no wa Rock da ze!\" ini dengan Mini live secara streaming. Para member membawakan semua lagu dari single ini (dengan catatan tanpa Higuchi Hina dan Wada Maaya yang telah lulus) termasuk performance pertama kalinya dari lagu \"Passion Fruits\" dan \"Yume o Miru Kinniku\" yang dibawakan oleh unit baru dengan nama Nogi Keionbun. Juga disini yang ditunggu-tunggu datang juga, mereka memperlihatkan uniform terbarunya.",
	"14" : "Di akhir tahun 2022, MoeFang mencoba menutup konten supporter spesial dengan garapan konser Manatsu no Zenkoku Tour 2019 di Nagoya Dome hari ke-2, dimana Aichi adalah perhentian pertama dalam perhelatan tur nasional ini sekaligus 4 hari sebelum Sakurai Reika mengumumkan kelulusannya. Adapun \"museum corner\" dimana disini menampilkan produksi khusus dan aransemen ulang lagu-lagu Nogizaka46.",
	"15" : "Setelah diselenggarakan juga acara yang sama pada single sebelumnya, Nogizaka46 kembali memperingati rilis single ke-31 Nogizaka46 \"Koko ni wa nai mono\" ini dengan Mini live secara streaming. Para member membawakan semua lagu dari single ini kecuali solo Saito Asuka yang juga tidak ikut serta karena telah mengakhiri kegiatannya 31 Desember 2022 lalu, yang mana posisi center main song ini dipegang oleh Endo Sakura. Mohon maaf bila ada salah terjemahan.",
	"16" : "Memperingati ulang tahunnya yang ke-11, Nogizaka46 mengadakan acara tahunannya yaitu 11th Birthday Live di Yokohama Arena selama 5 hari. Dalam 5 hari tersebut, hari pertama adalah penampilan seluruh member. Day 1 ini adalah sejarah Nogizaka46 dimana untuk terakhir kalinya BDL diikuti oleh dari generasi ke-1 hingga generasi ke-5.",
	"17" : "Memperingati ulang tahunnya yang ke-11, Nogizaka46 mengadakan acara tahunannya yaitu 11th Birthday Live di Yokohama Arena selama 5 hari. Dalam 5 hari tersebut, hari kedua adalah penampilan dari gen-5. Day 2 ini merupakan kedua kalinya gen-5 mengikuti konser ulang tahun Nogizaka46.",
	"18" : "Memperingati ulang tahunnya yang ke-11, Nogizaka46 mengadakan acara tahunannya yaitu 11th Birthday Live di Yokohama Arena selama 5 hari. Dalam 5 hari tersebut, hari ketiga adalah penampilan dari gen-4. Day 3 ini dihadiri 15 member gen-4 tanpa Kakehashi Sayaka.",
	"19" : "Memperingati ulang tahunnya yang ke-11, Nogizaka46 mengadakan acara tahunannya yaitu 11th Birthday Live di Yokohama Arena selama 5 hari. Dalam 5 hari tersebut, hari keempat adalah penampilan dari gen-3, sang pemimpin era baru Nogizaka46. Day 4 ini dihadiri 11 member gen-3.",
	"20" : "Memperingati ulang tahunnya yang ke-11, Nogizaka46 mengadakan acara tahunannya yaitu 11th Birthday Live di Yokohama Arena selama 5 hari. Dalam 5 hari tersebut, hari kelima atau hari terakhir ini adalah konser kelulusan kapten kedua, Akimoto Manatsu sekaligus gen-1 terakhir. Di bagian akhir seperti biasa akan ada pesan-pesan dari member ke Manatsu, dan Manatsu ke Umezawa Minami yang kini menjadi kapten ketiga.",
	"21" : "Setelah kita menangis dengan kepergiannya Akimoto Manatsu di konser ulang tahun sebelumnya, kini kita dihadirkan Graduation Ceremony dari Suzuki Ayane, member terakhir dari gen-2. Bicara soal \"Ceremony\", tentunya porsi bincang-bincang dengan para member lebih banyak dibandingkan penampilan lagu. Jadi, disini Ayane-chan membagi 3 sesi yang khusus dibuat oleh Ayane-chan. Seperti apakah itu? Segera siapkan tisu, ya.",
	"22" : "Underlive pada single ke-32 \"Hito wa Yume o Nido Miru\" menandakan partisipasi gen-5 yang tidak masuk senbatsu untuk pertama kalinya. Serangkaian penampilan di berbagai kota, berakhir kembali di Tokyo dan tayangan streaming hanya tersedia pada DAY 2 ini. Tidak hanya fresh, tapi juga kita melihat Underlive yang mulai dipimpin oleh gen-3.",
	"23" : "Hinatazaka46 4th-gen Omotenashikai merupakan live pertama yang dilakukan hanya oleh para member baru Hinatazaka46 yaitu 12 member gen-4. Diadakan pada tanggal 11 dan 12 Februari 2023 di Makuhari Messe Event Hall, dengan DAY 2 disiarkan secara streaming. Kita disini bisa melihat penampilan Omotenashi dan juga mini live di paruh kedua live.",
	"24" : "Saito Asuka, gen-1 termuda yang kini paling terakhir mengadakan konser kelulusannya di bulan Mei. Dalam setlist-nya baik hari pertama dan kedua dirancang berbeda oleh Asuka sendiri dan para staff. Disini tidak ketinggalan juga membawakan lagu-lagu unit khususnya yang pernah Asuka ikut serta dalam lagunya, juga lagu masa-masa ia menjadi Under member.",
	"25" : "Saito Asuka, gen-1 termuda yang kini paling terakhir mengadakan konser kelulusannya di bulan Mei. Dalam setlist-nya baik hari pertama dan kedua dirancang berbeda oleh Asuka sendiri dan para staff. Disini tidak ketinggalan juga membawakan lagu-lagu unit khususnya yang pernah Asuka ikut serta dalam lagunya, juga lagu masa-masa ia menjadi Under member.",
	"26" : "Setelah diselenggarakan juga acara yang sama pada single sebelumnya, Nogizaka46 kembali memperingati rilis single ke-32 \"Hito wa Yume o Nido Miru\" ini dengan Mini live secara streaming. Sebuah single dengan wajah Nogizaka baru dengan formasi senbatsu gen-3,4 dan 5, para member membawakan semua lagu dari single ini kecuali lagu kelulusan Akimoto Manatsu 'Bokutachi no Sayonara'.",
	"27" : "Sakurazaka46 mengadakan turnya yang ke-3 di tahun 2023, dan berakhir di Osaka-Jo Hall pada tanggal 1 Juni 2023 lalu. Disini mereka membawakan 21 lagu, termasuk lagu di single barunya, \"Start over!\".",
	"28" : "Di bulan ini, MoeFang mencoba menggarap konten supporter spesial dengan garapan konser Manatsu no Zenkoku Tour 2016 di Xebio Arena Sendai hari ke-2, dimana Saito Asuka bertugas menjadi kapten dalam tur ini karena saat itu telah terpilih untuk pertama kalinya menjadi center dalam single ke-15 \"Hadashi de Summer\".",
	"29" : "Kali ini kami menggarap Graduation Ceremony dari Hayakawa Seira, member kedua dari gen-4 yang mengumumkan kelulusannya setelah Kitagawa Yuri. Upacara kelulusan ini diadakan saat encore Manatsu no Zenkoku Tour 2023 Osaka Performance, jadi waktunya singkat, tidak seperti biasanya. Akan ada beberapa lagu, termasuk pesan dari perwakilan tiap generasi.",
	"30" : "Di bulan ini, MoeFang mencoba menggarap konten supporter spesial dengan garapan konser Manatsu no Zenkoku Tour 2023 di Jingu Baseball Stadium, dimana untuk pertama kalinya Nogizaka46 mengadakan konser final Zenkoku Tour-nya dalam kurun waktu 4 hari berturut-turut.",
	"31" : "Di bulan ini, MoeFang mencoba menggarap konten supporter spesial dengan garapan konser Manatsu no Zenkoku Tour 2023 di Jingu Baseball Stadium, dimana untuk pertama kalinya Nogizaka46 mengadakan konser final Zenkoku Tour-nya dalam kurun waktu 4 hari berturut-turut.",
	"32" : "Di bulan ini, MoeFang mencoba menggarap konten supporter spesial dengan garapan konser Manatsu no Zenkoku Tour 2023 di Jingu Baseball Stadium, dimana untuk pertama kalinya Nogizaka46 mengadakan konser final Zenkoku Tour-nya dalam kurun waktu 4 hari berturut-turut.",
	"33" : "Di bulan ini, MoeFang mencoba menggarap konten supporter spesial dengan garapan konser Manatsu no Zenkoku Tour 2023 di Jingu Baseball Stadium, dimana untuk pertama kalinya Nogizaka46 mengadakan konser final Zenkoku Tour-nya dalam kurun waktu 4 hari berturut-turut.",
	"34" : "Di bulan ini, MoeFang mencoba menggarap konten supporter spesial dengan garapan konser 33rd SG Underlive DAY 3 yang diadakan di Yokohama Arena, dan juga termasuk Jikochuu Produce-nya di DAY 1 dan DAY 2. Underlive ini diklaim sebagai konser Underlive terbesar dibandingkan sebelumnya.",
	"35" : "Setelah diselenggarakan juga acara yang sama pada single sebelumnya, Nogizaka46 kembali memperingati rilis single ke-33 \"Ohitorisama Tengoku\" ini dengan Mini live secara streaming. Sebuah single dengan wajah Nogizaka baru dengan formasi center gen-5 untuk kedua kalinya, yaitu Inoue Nagi yang pertama kali menjadi center.",
	"36" : "Dalam konser 'Shinzanmono Live at THEATER MILANO-Za' ini, setiap grup Sakamichi menampilkan pertunjukan baru oleh generasi barunya masing-masing, dengan total 30 pertunjukan, di mana setiap grup memiliki 10 pertunjukan. Pertunjukan terakhir diadakan pada 30 November oleh Hinatazaka46 gen-4, 2 Desember oleh Sakurazaka46 gen-3, dan keesokan harinya oleh Nogizaka46 gen-5.<",
	"37" : "Dalam konser 'Shinzanmono Live at THEATER MILANO-Za' ini, setiap grup Sakamichi menampilkan pertunjukan baru oleh generasi barunya masing-masing, dengan total 30 pertunjukan, di mana setiap grup memiliki 10 pertunjukan. Pertunjukan terakhir diadakan pada 30 November oleh Hinatazaka46 gen-4, 2 Desember oleh Sakurazaka46 gen-3, dan keesokan harinya oleh Nogizaka46 gen-5.<",
	"38" : "Dalam konser 'Shinzanmono Live at THEATER MILANO-Za' ini, setiap grup Sakamichi menampilkan pertunjukan baru oleh generasi barunya masing-masing, dengan total 30 pertunjukan, di mana setiap grup memiliki 10 pertunjukan. Pertunjukan terakhir diadakan pada 30 November oleh Hinatazaka46 gen-4, 2 Desember oleh Sakurazaka46 gen-3, dan keesokan harinya oleh Nogizaka46 gen-5.<",
	"39" : "Dalam konser 'Shinzanmono Live at THEATER MILANO-Za' ini, setiap grup Sakamichi menampilkan pertunjukan baru oleh generasi barunya masing-masing, dengan total 30 pertunjukan, di mana setiap grup memiliki 10 pertunjukan. Pertunjukan terakhir diadakan pada 30 November oleh Hinatazaka46 gen-4, 2 Desember oleh Sakurazaka46 gen-3, dan keesokan harinya oleh Nogizaka46 gen-5.<",
	"40" : "Dalam konser 'Shinzanmono Live at THEATER MILANO-Za' ini, setiap grup Sakamichi menampilkan pertunjukan baru oleh generasi barunya masing-masing, dengan total 30 pertunjukan, di mana setiap grup memiliki 10 pertunjukan. Pertunjukan terakhir diadakan pada 30 November oleh Hinatazaka46 gen-4, 2 Desember oleh Sakurazaka46 gen-3, dan keesokan harinya oleh Nogizaka46 gen-5.<",
	"41" : "Dalam konser 'Shinzanmono Live at THEATER MILANO-Za' ini, setiap grup Sakamichi menampilkan pertunjukan baru oleh generasi barunya masing-masing, dengan total 30 pertunjukan, di mana setiap grup memiliki 10 pertunjukan. Pertunjukan terakhir diadakan pada 30 November oleh Hinatazaka46 gen-4, 2 Desember oleh Sakurazaka46 gen-3, dan keesokan harinya oleh Nogizaka46 gen-5.<",
	"42" : "Grup rival Nogizaka46, Boku ga Mitakatta Aozora, mengadakan one man live dengan tajuk \"Boku ga Mitakatta One Man Live vol.0\" pada 19 Agustus 2023 silam. Disini mereka membawakan seluruh lagunya dalam single debut mereka, juga membawakan untuk pertama kalinya single kedua.",
	"43" : "Memperingati ulang tahunnya yang ke-12, Nogizaka46 mengadakan acara tahunannya yaitu 12th Birthday Live di Saitama Super Arena selama 4 hari. Setiap harinya mereka membawakan setlist yang berbeda-beda dengan total 123 lagu, meringkas sejarah Nogizaka dari single pertama hingga single terbaru yang ke-35. Hari ke-1 mereka membawakan lagu dari single yang dirilis tahun 2011 hingga 2014, dimana gen-3, 4 dan 5 belum berpartisipasi di single tersebut.",
	"44" : "Memperingati ulang tahunnya yang ke-12, Nogizaka46 mengadakan acara tahunannya yaitu 12th Birthday Live di Saitama Super Arena selama 4 hari. Setiap harinya mereka membawakan setlist yang berbeda-beda dengan total 123 lagu, meringkas sejarah Nogizaka dari single pertama hingga single terbaru yang ke-35. Hari ke-2 mereka membawakan lagu dari single yang dirilis tahun 2015 hingga 2017, dimana gen-3 untuk pertama kalinya bergabung saat itu.",
	"45" : "Memperingati ulang tahunnya yang ke-12, Nogizaka46 mengadakan acara tahunannya yaitu 12th Birthday Live di Saitama Super Arena selama 4 hari. Setiap harinya mereka membawakan setlist yang berbeda-beda dengan total 123 lagu, meringkas sejarah Nogizaka dari single pertama hingga single terbaru yang ke-35. Hari ke-3 mereka membawakan lagu dari single yang dirilis tahun 2018 hingga 2020, dimana gen-4 untuk pertama kalinya bergabung saat itu.",
	"46" : "Memperingati ulang tahunnya yang ke-12, Nogizaka46 mengadakan acara tahunannya yaitu 12th Birthday Live di Saitama Super Arena selama 4 hari. Setiap harinya mereka membawakan setlist yang berbeda-beda dengan total 123 lagu, meringkas sejarah Nogizaka dari single pertama hingga single terbaru yang ke-35. Hari ke-4 mereka membawakan lagu dari single yang dirilis tahun 2021 hingga 2024, dimana gen-5 untuk pertama kalinya bergabung saat itu.",
	"47" : "Setelah diselenggarakan juga acara yang sama pada single sebelumnya, Nogizaka46 kembali memperingati rilis single ke-34 \"Monopoly\" ini dengan Mini live secara streaming. Sebuah single dengan kembali menampilkan wajah W-center Nogizaka baru, yaitu Kaki Haruka dan Endo Sakura.",
	"48" : "Kali ini kami menggarap Graduation Concert dari Yamashita Mizuki, ace Nogizaka46 dari gen-3 yang mengumumkan kelulusannya di single ke-35 ini. Konser kelulusan ini diadakan selama 2 hari di Tokyo Dome. Akan ada banyak lagu dan segmen spesial dari Mizuki sendiri, juga pesan dari perwakilan tiap generasi.",
	"49" : "Setelah diselenggarakan juga acara yang sama pada single sebelumnya, Nogizaka46 kembali memperingati rilis single ke-35 \"Chance wa Byoudou\" ini dengan Mini live secara streaming. Sebuah single kelulusan dengan center Yamashita Mizuki, yang pada mini live ini diganti oleh Kubo Shiori dan Umezawa Minami. Juga, setelah mini live diadakan graduation ceremony untuk Sakaguchi Tamami dan Seimiya Rei yang memutuskan lulus pada single ini. Tak lupa juga ada pesan untuk mereka berdua dari masing-masing generasi.",
	"50" : "Kakehashi Sayaka dari generasi 4 kembali ke Nogizaka46 setelah hiatus hampir 2 tahun lamanya, namun tidak untuk kembali beraktifitas, melainkan untuk mengumumkan kelulusannya dari Nogizaka dan menarik diri dari dunia entertainment. Meskipun awalnya hanya pengumuman kelulusan saja, namun Saachan ingin memberikan penampilan terakhirnya bersama gen-4 pada para penggemarnya, melalui Graduation Ceremony yang disiarkan lewat YouTube resmi Nogizaka46.",
	"51" : "Toa, ketua klub paduan suara yang hanya memiliki enam anggota, bersama para anggota lainnya berusaha mengatasi situasi di mana mereka tidak memenuhi jumlah anggota yang diperlukan untuk mengikuti kompetisi. Mereka mencoba mengajak Aoi, yang belajar di kelas piano yang sama dengan Suzuki, kapten klub tari, untuk ikut serta dalam kompetisi paduan suara sebagai bantuan. Toa dan Suzuki sangat menantikan kompetisi paduan suara dan pelatihan musim panas, tetapi pada perjalanan pulang hari itu, Suzuki mengalami kecelakaan dan tidak pernah kembali. Pada hari itu, karena membiarkan Suzuki pulang lebih dulu, Toa dan yang lainnya menjalani hari-hari penuh penyesalan di dunia tanpa Suzuki.",
	"52" : "Konser final tur nasional tahunan Nogizaka46, \"Manatsu no Zenkoku Tour 2024,\" digelar di Stadion Baseball Meiji Jingu, Tokyo, pada 2-4 September. Tur ini mencakup 7 pertunjukan di tiga lokasi berbeda, dimulai di Osaka pada Juli dan diakhiri di Tokyo, dengan total penonton mencapai 265.000 orang. Meskipun sempat terancam oleh Topan No. 10, konser berjalan lancar dan memukau penonton dengan penampilan energik para member dari gen-3 hingga gen-5. Konser diwarnai dengan berbagai pertunjukan, kostum, dan interaksi dengan penonton, diakhiri dengan encore emosional yang membuat penonton terpukau.",
	"53" : "Konser final tur nasional tahunan Nogizaka46, \"Manatsu no Zenkoku Tour 2024,\" digelar di Stadion Baseball Meiji Jingu, Tokyo, pada 2-4 September. Tur ini mencakup 7 pertunjukan di tiga lokasi berbeda, dimulai di Osaka pada Juli dan diakhiri di Tokyo, dengan total penonton mencapai 265.000 orang. Meskipun sempat terancam oleh Topan No. 10, konser berjalan lancar dan memukau penonton dengan penampilan energik para member dari gen-3 hingga gen-5. Konser diwarnai dengan berbagai pertunjukan, kostum, dan interaksi dengan penonton, diakhiri dengan encore emosional yang membuat penonton terpukau.",
	"54" : "Konser final tur nasional tahunan Nogizaka46, \"Manatsu no Zenkoku Tour 2024,\" digelar di Stadion Baseball Meiji Jingu, Tokyo, pada 2-4 September. Tur ini mencakup 7 pertunjukan di tiga lokasi berbeda, dimulai di Osaka pada Juli dan diakhiri di Tokyo, dengan total penonton mencapai 265.000 orang. Meskipun sempat terancam oleh Topan No. 10, konser berjalan lancar dan memukau penonton dengan penampilan energik para member dari gen-3 hingga gen-5. Konser diwarnai dengan berbagai pertunjukan, kostum, dan interaksi dengan penonton, diakhiri dengan encore emosional yang membuat penonton terpukau.",
	"55" : "Boku ga Mitakatta Aozora merayakan ulang tahun pertama debut mereka dengan menggelar konser \"Aozora Summer Festival 2024\" pada 30 Agustus 2024 di Toyosu PIT, Tokyo. Konser ini menampilkan total 16 lagu termasuk tiga lagu yang pertama kali dibawakan, yaitu \"Ano Hi Bokutachi wa Naiteita,\" \"Boku ni Totte wa,\" dan lagu tema dari anime \"Ganbatte Ikimasshoi,\" \"Sorairo no Mizushibuki.\" Selain itu, konser ini juga menampilkan shuffle unit song yang belum pernah dilakukan sebelumnya dan berbagai aktivitas bertema festival musim panas.",
	"56" : "Pada 27 November, member under group Nogizaka46 mengadakan konser final ‘34th SG Under Live’ di Pia Arena MM, Kanagawa, dengan 30.000 penggemar yang hadir selama tiga hari dan penayangan daring di hari terakhir. Konser ini menampilkan lagu-lagu dari single terbaru \"Monopoly,\" termasuk penampilan dari 14 member under, seperti Nakanishi Aruno yang memimpin dengan semangat, memulai lagu pembuka “Machine Gun Rain” dalam kostum merah yang mencolok. Di konser ini, member menampilkan lagu-lagu penuh energi, diiringi tarian, drum session, serta panggung bertema yang berbeda dari konser biasa. Aruno mengungkapkan harapannya untuk menjadikan under live ini “terbaik” dan menutup konser dengan lagu \"Omoide ga Tomaranakunaru\" penuh senyum ceria setelah lagu sebelumnya “Actually...” yang lebih serius. Dalam encore yang hangat, para member tampil dekat dengan penonton, dan fans memberikan dukungan luar biasa dengan nyanyian bersama “Nogizaka no Uta.” Konser berakhir emosional ketika Aruno dan member lain, berpegangan tangan, mengucapkan terima kasih kepada penggemar dalam suara mereka sendiri tanpa mikrofon, menandai penutupan tiga hari konser dengan penuh kesan.",
	"57" : "Pada 9 Juni, konser akhir '35th SG Under Live' dari Nogizaka46 digelar di Ariake Arena, menampilkan lagu-lagu dari single ke-35 “Chance wa Byoudou”. Untuk pertama kalinya, konser ini hanya diikuti oleh member generasi ke-4 dan ke-5. Selama tiga hari, para member memukau penonton dengan tarian, nyanyian, dan interaksi penuh semangat. Pada hari terakhir, Tsutsui Ayame, sang pemimpin, menyampaikan tekad kuatnya untuk mempertahankan semangat tim dan menginspirasi perubahan. Konser diisi berbagai unit performance dan kegiatan menarik yang melibatkan permainan fisik, memperlihatkan sisi unik setiap member. Ayame menyatakan mimpinya untuk menjadi “agen perubahan” di Nogizaka46, dan menutup acara dengan lagu \"Shadougawa\", penuh emosi dan semangat. Penampilan encore termasuk \"Jumping Joker Flash\", sementara keseluruhan konser menunjukkan tekad mereka untuk meneruskan warisan para senior sambil meraih masa depan yang lebih besar di bawah bendera Nogizaka46.",
	"58" : "Setelah diselenggarakan juga acara yang sama pada single sebelumnya, Nogizaka46 kembali memperingati rilis single ke-36 \"Cheat Day\" ini dengan Mini live secara streaming. Sebuah single tema musim panas dengan front gen-5, Ogawa Aya yang langsung berada di front dan Ikeda Teresa, menemani sang center Inoue Nagi, yang kembali terpilih untuk kedua kalinya memimpin single bertemakan musim panas.",
	"59" : "Setelah diselenggarakan juga acara yang sama pada single sebelumnya, Nogizaka46 kembali memperingati rilis single ke-37 \"Hodoukyou\" ini dengan Mini live secara streaming. Sebuah single tema musim dingin dengan center Endo Sakura, yang kembali terpilih untuk keempat kalinya.",
	"60": "Kali ini kami menggarap Graduation Concert dari Yoda Yuuki dari gen-3 yang mengumumkan kelulusannya di single ke-37 awal tahun 2025. Konser kelulusannya diadakan selama 2 hari di PayPay Dome Fukuoka, prefektur kelahirannya. Hari pertama Yoda membuat tema 'sebelum hari kelulusan', yaitu semua segmen di dalamnya terserah keinginan Yoda seperti apa. Dan hari kedua adalah hari kelulusannya, alias graduation concert yang serius. Yang membedakannya, konser kelulusannya Yoda dihadiri berbagai bintang tamu yang pernah bersama dengan Yoda, bahkan lulusan gen-3, Ozono Momoko tiba-tiba muncul menemani Yoda dalam 'Nigemizu' untuk yang terakhir kalinya.",
};

// =======================
// NAMA ACARA
// =======================


const nameShow = {
	"01" : "ノギザカスキッツ LIVE",
	"02" : "乃木坂46 アンダーライブ 2021",
	"03" : "@JAM EXPO 2020-2021",
	"04" : "乃木坂46 28th SG アンダーライブ",
	"05" : "乃木坂46 28thシングル「君に叱られた」発売記念ミニライブ",
	"06" : "乃木坂46 第2回 5期生 お見立て会",
	"07" : "乃木坂46 10th YEAR BIRTHDAY LIVE",
	"08" : "乃木坂46 29thシングル「Actually...」発売記念ミニライブ",
	"09" : "乃木坂46北野日奈子卒業コンサート",
	"10" : "Tokyo Idol Festival 2022",
	"11" : "乃木坂46 1st YEAR BIRTHDAY LIVE",
	"12" : "乃木坂46 樋口日奈卒業セレモニー",
	"13" : "乃木坂46 30thシングル「好きというのはロックだぜ！」発売記念ミニライブ",
	"14" : "乃木坂46 真夏の全国ツアー2019 @ 名古屋ドーム DAY 2",
	"15" : "乃木坂46 31stシングル「ここにはないもの」発売記念ミニライブ",
	"16" : "乃木坂46 11th YEAR BIRTHDAY LIVE",
	"17" : "乃木坂46 11th YEAR BIRTHDAY LIVE -5th Members Live-",
	"18" : "乃木坂46 11th YEAR BIRTHDAY LIVE -4th Members Live-",
	"19" : "乃木坂46 11th YEAR BIRTHDAY LIVE -3rd Members Live-",
	"20" : "乃木坂46 11th YEAR BIRTHDAY LIVE -秋元真夏卒業コンサート-",
	"21" : "乃木坂46 鈴木絢音卒業セレモニー",
	"22" : "乃木坂46 32nd SG アンダーライブ",
	"23" : "日向坂46 4期生おもてなし会",
	"24" : "乃木坂46 齋藤飛鳥卒業コンサート DAY 1",
	"25" : "乃木坂46 齋藤飛鳥卒業コンサート DAY 2",
	"26" : "乃木坂46 32ndシングル「人は夢を二度見る」発売記念ミニライブ",
	"27" : "3rd Tour 2023 Sakurazaka46",
	"28" : "乃木坂46 真夏の全国ツアー 2016 ゼビオアリーナ仙台 DAY 2 昼公演",
	"29" : "乃木坂46 早川聖来卒業セレモニー",
	"30" : "乃木坂46 真夏の全国ツアー 2023 in 東京 @ 明治神宮 DAY 1",
	"31" : "乃木坂46 真夏の全国ツアー 2023 in 東京 @ 明治神宮 DAY 2",
	"32" : "乃木坂46 真夏の全国ツアー 2023 in 東京 @ 明治神宮 DAY 3",
	"33" : "乃木坂46 真夏の全国ツアー 2023 in 東京 @ 明治神宮 DAY 4",
	"34" : "乃木坂46 33rd SG アンダーライブ",
	"35" : "乃木坂46 33rdシングル「おひとりさま天国」発売記念ミニライブ",
	"36" : "Shinzanmono LIVE at THEATER MILANO-Za",
	"37" : "Shinzanmono LIVE at THEATER MILANO-Za",
	"38" : "Shinzanmono LIVE at THEATER MILANO-Za",
	"39" : "Shinzanmono LIVE at THEATER MILANO-Za",
	"40" : "Shinzanmono LIVE at THEATER MILANO-Za",
	"41" : "Shinzanmono LIVE at THEATER MILANO-Za",
	"42" : "僕が観たかったワンマンライブ vol.0",
	"43" : "乃木坂46 12th YEAR BIRTHDAY LIVE DAY 1",
	"44" : "乃木坂46 12th YEAR BIRTHDAY LIVE DAY 2",
	"45" : "乃木坂46 12th YEAR BIRTHDAY LIVE DAY 3",
	"46" : "乃木坂46 12th YEAR BIRTHDAY LIVE DAY 4",
	"47" : "乃木坂46 34thシングル「Monopoly」発売記念ミニライブ",
	"48" : "乃木坂46 山下美月卒業コンサート",
	"49" : "乃木坂46 35thシングル「チャンスは平等」発売記念ミニライブ & 阪口珠美-清宮レイ卒業セレモニー",
	"50" : "乃木坂46 掛橋沙耶香卒業セレモニー",
	"51" : "僕が見たかった青空　舞台「夏霞～NATSUGASUMI～」 昼の部（B）",
	"52" : "乃木坂46 真夏の全国ツアー 2024 in 東京 @ 明治神宮 DAY 1",
	"53" : "乃木坂46 真夏の全国ツアー 2024 in 東京 @ 明治神宮 DAY 2",
	"54" : "乃木坂46 真夏の全国ツアー 2024 in 東京 @ 明治神宮 DAY 3",
	"55" : "僕が見たかった青空 アオゾラサマーフェスティバル2024",
	"56" : "乃木坂46 34th SG アンダーライブ",
	"57" : "乃木坂46 35th SG アンダーライブ",
	"58" : "乃木坂46 36thシングル「チートデイ」発売記念ミニライブ",
	"59" : "乃木坂46 37thシングル「歩道橋」発売記念ミニライブ",
	"60" : "乃木坂46 与田祐希卒業コンサート",
};
console.log(nameShow);


// =======================
// EPISODE
// =======================

const descEpisode = {
	"01" : "| Nogizaka Skits Live",
	"02" : "| Nogizaka46 Under Live 2021 (Miria & Junna Graduation)",
	"03" : "| Nogizaka46 Gen-4 @JAM EXPO 2020-2021",
	"04" : "| Nogizaka46 28th SG Underlive 2021 (Terada Ranze Graduation)",
	"05" : "| Nogizaka46 Mini Live 28th Single \"Kimi ni Shikarareta\"",
	"06" : "| Nogizaka46 5th-gen 2nd Omitatekai",
	"07" : "| Nogizaka46 10th Year Birthday Live DAY 2",
	"08" : "| Nogizaka46 Mini Live 29th Single \"Actually...\"",
	"09" : "| Nogizaka46 Kitano Hinako Graduation Concert",
	"10" : "| Nogizaka46 Gen-5 @TIF 2022",
	"11" : "| Nogizaka46 1st Year Birthday Live",
	"12" : "| Nogizaka46 Higuchi Hina Graduation Ceremony",
	"13" : "| Nogizaka46 Mini Live 30th Single \"Suki to Iu no wa Rock daze!\"",
	"14" : "| Nogizaka46 Manatsu no Zenkoku Tour 2019 @ Nagoya Dome Day 2",
	"15" : "| Nogizaka46 Mini Live 31st Single \"Koko ni wa nai mono\"",
	"16" : "| Nogizaka46 11th Year Birthday Live DAY 1",
	"17" : "| Nogizaka46 11th Year Birthday Live DAY 2 (Gen-5)",
	"18" : "| Nogizaka46 11th Year Birthday Live DAY 3 (Gen-4)",
	"19" : "| Nogizaka46 11th Year Birthday Live DAY 4 (Gen-3)",
	"20" : "| Nogizaka46 11th Year Birthday Live DAY 5 (Akimoto Manatsu Graduation Concert)",
	"21" : "| Nogizaka46 Suzuki Ayane Graduation Ceremony",
	"22" : "| Nogizaka46 32nd SG Underlive",
	"23" : "| Hinatazaka46 4th-gen Omotenashikai",
	"24" : "| Nogizaka46 Saito Asuka Graduation Concert DAY 1",
	"25" : "| Nogizaka46 Saito Asuka Graduation Concert DAY 2",
	"26" : "| Nogizaka46 Mini Live 32nd Single \"Hito wa Yume o Nido Miru\"",
	"27" : "| Sakurazaka46 3rd Tour 2023",
	"28" : "| Nogizaka46 Manatsu no Zenkoku Tour 2016 @ Xebio Arena Day 2",
	"29" : "| Nogizaka46 Hayakawa Seira Graduation Ceremony",
	"30" : "| Nogizaka46 Manatsu no Zenkoku Tour 2023 DAY 1",
	"31" : "| Nogizaka46 Manatsu no Zenkoku Tour 2023 DAY 2",
	"32" : "| Nogizaka46 Manatsu no Zenkoku Tour 2023 DAY 3",
	"33" : "| Nogizaka46 Manatsu no Zenkoku Tour 2023 DAY 4",
	"34" : "| Nogizaka46 33rd SG Underlive",
	"35" : "| Nogizaka46 Mini Live 33rd Single \"Ohitorisama Tengoku\"",
	"36" : "| Shinzanmono LIVE at THEATER MILANO-Za",
	"37" : "| Shinzanmono LIVE at THEATER MILANO-Za",
	"38" : "| Shinzanmono LIVE at THEATER MILANO-Za",
	"39" : "| Shinzanmono LIVE at THEATER MILANO-Za",
	"40" : "| Shinzanmono LIVE at THEATER MILANO-Za",
	"41" : "| Shinzanmono LIVE at THEATER MILANO-Za",
	"42" : "| Boku ga Mitakatta One Man Live Vol.0",
	"43" : "| Nogizaka46 12th Year Birthday Live DAY 1",
	"44" : "| Nogizaka46 12th Year Birthday Live DAY 2",
	"45" : "| Nogizaka46 12th Year Birthday Live DAY 3",
	"46" : "| Nogizaka46 12th Year Birthday Live DAY 4",
	"47" : "| Nogizaka46 Mini Live 34th Single \"Monopoly\"",
	"48" : "| Nogizaka46 Yamashita Mizuki Graduation Concert",
	"49" : "| Nogizaka46 Mini Live 35th Single \"Chance wa Byoudou\" & Sakaguchi Tamami-Seimiya Rei Graduation Ceremony",
	"50" : "| Nogizaka46 Kakehashi Sayaka Graduation Ceremony",
	"51" : "| Boku ga Mitakatta Aozora Stageplay \"NATSUGASUMI\"",
	"52" : "| Nogizaka46 Manatsu no Zenkoku Tour 2024 FINAL! in Tokyo DAY 1",
	"53" : "| Nogizaka46 Manatsu no Zenkoku Tour 2024 FINAL! in Tokyo DAY 2",
	"54" : "| Nogizaka46 Manatsu no Zenkoku Tour 2024 FINAL! in Tokyo DAY 3",
	"55" : "| Boku ga Mitakatta Aozora \"Aozora Summer Festival 2024\"",
	"56" : "| Nogizaka46 34th SG Underlive",
	"57" : "| Nogizaka46 35th SG Underlive",
	"58" : "| Nogizaka46 Mini Live 36th Single \"Cheat Day\"",
	"59" : "| Nogizaka46 Mini Live 37th Single \"Hodoukyou\"",
	"60" : "| Nogizaka46 Yoda Yuuki Graduation Concert",
};
console.log(descEpisode);

// =======================
// DESKRIPSI AIRING
// =======================

const descOnAirDate = {
	"01" : "18 April 2021",
	"02" : "26 Mei 2021",
	"03" : "27 Agustus 2021",
	"04" : "28 Oktober 2021",
	"05" : "29 November 2021",
	"06" : "27 April 2022",
	"07" : "15 Mei 2022",
	"08" : "19 Juni 2021",
	"09" : "24 Maret 2022",
	"10" : "7 Agustus 2022",
	"11" : "22 Februari 2013",
	"12" : "31 Oktober 2022",
	"13" : "27 November 2022",
	"14" : "4 Juli 2019",
	"15" : "6 Maret 2023",
	"16" : "22 Februari 2023",
	"17" : "23 Februari 2023",
	"18" : "24 Februari 2023",
	"19" : "25 Februari 2023",
	"20" : "26 Februari 2023",
	"21" : "28 Maret 2023",
	"22" : "27 April 2023",
	"23" : "12 Februari 2023",
	"24" : "17 Mei 2023",
	"25" : "18 Mei 2023",
	"26" : "3 Juni 2023",
	"27" : "1 Juni 2023",
	"28" : "14 Agustus 2016",
	"29" : "13 Juli 2023",
	"30" : "25 Agustus 2023",
	"31" : "26 Agustus 2023",
	"32" : "27 Agustus 2023",
	"33" : "28 Agustus 2023",
	"34" : "1 Oktober 2023",
	"35" : "18 Oktober 2023",
	"36" : "12 November 2023",
	"37" : "18 November 2023",
	"38" : "27 November 2023",
	"39" : "30 November 2023",
	"40" : "2 Desember 2023",
	"41" : "3 Desember 2023",
	"42" : "19 Desember 2023",
	"43" : "7 Maret 2024",
	"44" : "8 Maret 2024",
	"45" : "9 Maret 2024",
	"46" : "10 Maret 2024",
	"47" : "21 Maret 2024",
	"48" : "11-12 Mei 2024",
	"49" : "15 Juli 2024",
	"50" : "19 Agustus 2024",
	"51" : "21 Juli 2024",
	"52" : "2 September 2024",
	"53" : "3 September 2024",
	"54" : "4 September 2024",
	"55" : "20 September 2024",
	"56" : "27 Januari 2024",
	"57" : "9 Juni 2024",
	"58" : "23 November 2024",
	"59" : "11 Januari 2025",
	"60" : "22-23 Februari 2025",
};
console.log(descOnAirDate);


// =======================
// PARTISIPASI ORANG & TAMU
// =======================

const memberParticipate = {
	"01" : "乃木坂46 3期生 & 4期生",
	"02" : "乃木坂46 ",
	"03" : "乃木坂46 4期生",
	"04" : "乃木坂46  28枚目シングルアンダーメンバー",
	"05" : "乃木坂46 ",
	"06" : "乃木坂46 5期生、秋元真夏、梅澤美波",
	"07" : "乃木坂46 ",
	"08" : "乃木坂46 ",
	"09" : "乃木坂46 ",
	"10" : "乃木坂46 5期生",
	"11" : "乃木坂46 ",
	"12" : "乃木坂46 ",
	"13" : "乃木坂46 ",
	"14" : "乃木坂46 ",
	"15" : "乃木坂46 ",
	"16" : "乃木坂46 ",
	"17" : "乃木坂46 5期生",
	"18" : "乃木坂46 4期生",
	"19" : "乃木坂46 3期生",
	"20" : "乃木坂46 ",
	"21" : "乃木坂46 ",
	"22" : "乃木坂46  32枚目シングルアンダーメンバー",
	"23" : "日向坂46 4期生",
	"24" : "乃木坂46 ",
	"25" : "乃木坂46 ",
	"26" : "乃木坂46 ",
	"27" : "桜坂46",
	"28" : "乃木坂46 ",
	"29" : "乃木坂46 ",
	"30" : "乃木坂46 ",
	"31" : "乃木坂46 ",
	"32" : "乃木坂46 ",
	"33" : "乃木坂46 ",
	"34" : "乃木坂46  33枚目シングルアンダーメンバー",
	"35" : "乃木坂46 ",
	"36" : "桜坂46 3期生",
	"37" : "日向坂46 4期生",
	"38" : "乃木坂46 5期生",
	"39" : "日向坂46 4期生",
	"40" : "桜坂46 3期生",
	"41" : "乃木坂46 5期生",
	"42" : "僕が見たかった青空",
	"43" : "乃木坂46 ",
	"44" : "乃木坂46 ",
	"45" : "乃木坂46 ",
	"46" : "乃木坂46 ",
	"47" : "乃木坂46 ",
	"48" : "乃木坂46 ",
	"49" : "乃木坂46 ",
	"50" : "乃木坂46 4期生",
	"51" : "僕が見たかった青空",
	"52" : "乃木坂46 ",
	"53" : "乃木坂46 ",
	"54" : "乃木坂46 ",
	"55" : "僕が見たかった青空",
	"56" : "乃木坂46 ",
	"57" : "乃木坂46 ",
	"58" : "乃木坂46 ",
	"59" : "乃木坂46 ",
	"60" : "乃木坂46 ",
};
console.log(memberParticipate);


// =======================
// IMAGE THUMBNAIL main
// =======================


const imageThumbBig = {
	"01" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogiskitslive.jpg",
	"02" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive2021.jpg",
	"03" : "https://ik.imagekit.io/mLsKqNSuB/post/live/jamexpo20-21.jpg",
	"04" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive28.jpg",
	"05" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive28.jpg",
	"06" : "https://ik.imagekit.io/mLsKqNSuB/post/live/omitatekai2.jpg",
	"07" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_10th-bdl2.jpg",
	"08" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive29.jpg",
	"09" : "https://ik.imagekit.io/mLsKqNSuB/post/live/kitanohinakogradcon.jpg",
	"10" : "https://ik.imagekit.io/mLsKqNSuB/post/live/tif2022nogizaka.jpg",
	"11" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_1st-bdl.jpg",
	"12" : "https://ik.imagekit.io/mLsKqNSuB/post/live/higuchinagradcon.jpg",
	"13" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive30.jpg",
	"14" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutoue2019nagoyaday2.jpg",
	"15" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive31.jpg",
	"16" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl1.jpg",
	"17" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl2.jpg",
	"18" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl3.jpg",
	"19" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl4.jpg",
	"20" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl5.jpg",
	"21" : "https://ik.imagekit.io/mLsKqNSuB/post/live/ayanegradcer.jpg",
	"22" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive32.jpg",
	"23" : "https://ik.imagekit.io/mLsKqNSuB/post/live/hinata4thomotenashikai.jpg",
	"24" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230517-asukasotsucon1.jpg",
	"25" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230517-asukasotsucon2.jpg",
	"26" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive32.jpg",
	"27" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230601-sakura3rdtourosaka2023.jpg",
	"28" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutoue2016xebiosendaiday2.jpg",
	"29" : "https://ik.imagekit.io/mLsKqNSuB/post/live/seiragradcer.jpg",
	"30" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023.jpg",
	"31" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023.jpg",
	"32" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023.jpg",
	"33" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023.jpg",
	"34" : "https://ik.imagekit.io/mLsKqNSuB/post/live/33rdunderlive.jpg",
	"35" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive33.jpg",
	"36" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231112-shinzanmono-sakurazaka46.jpg",
	"37" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231118-shinzanmono-hinatazaka46.jpg",
	"38" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231127-shinzanmono-nogizaka46.jpg",
	"39" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231130-shinzanmono-hinatazaka46.jpg",
	"40" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231202-shinzanmono-sakurazaka46.jpg",
	"41" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231203-shinzanmono-nogizaka46.jpg",
	"42" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231219-bokuao-oneman-vol0.jpg",
	"43" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl1.jpg",
	"44" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl2.jpg",
	"45" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl3.jpg",
	"46" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl4.jpg",
	"47" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive34.jpg",
	"48" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zukkigradcer.jpg",
	"49" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive35.jpg",
	"50" : "https://ik.imagekit.io/mLsKqNSuB/post/live/saachangradcer.jpg",
	"51" : "https://ik.imagekit.io/mLsKqNSuB/post/live/bokuaonatsugasumi.jpg",
	"52" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d1.jpg",
	"53" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d2.jpg",
	"54" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d3.jpg",
	"55" : "https://ik.imagekit.io/mLsKqNSuB/post/live/bokuao-aozorasummerfes2024.jpg",
	"56" : "https://ik.imagekit.io/mLsKqNSuB/post/live/34thunderlive.jpg",
	"57" : "https://ik.imagekit.io/mLsKqNSuB/post/live/35thunderlive.jpg",
	"58" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive36.jpg",
	"59" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive37.jpg",
	"60" : "https://ik.imagekit.io/mLsKqNSuB/post/live/yodagradcon.jpg",
};
console.log(imageThumbBig);


// =======================
// IMAGE THUMBNAIL A
// =======================

const imageThumbA = {
	"01" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogiskitslive1.jpg",
	"02" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive2021a.jpg",
	"03" : "https://ik.imagekit.io/mLsKqNSuB/post/live/jamexpo20-21a.jpg",
	"04" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive28a.jpg",
	"05" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive28a.jpg",
	"06" : "https://ik.imagekit.io/mLsKqNSuB/post/live/omitatekai2a.jpg",
	"07" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_10th-bdl2a.jpg",
	"08" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive29a.jpg",
	"09" : "https://ik.imagekit.io/mLsKqNSuB/post/live/kitanohinakogradcona.jpg",
	"10" : "https://ik.imagekit.io/mLsKqNSuB/post/live/tif2022nogizaka1.jpg",
	"11" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_1st-bdla.jpg",
	"12" : "https://ik.imagekit.io/mLsKqNSuB/post/live/higuchinagradcona.jpg",
	"13" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive30a.jpg",
	"14" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutoue2019nagoyaday2a.jpg",
	"15" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive31a.jpg",
	"16" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl1a.jpg",
	"17" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl2a.jpg",
	"18" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl3a.jpg",
	"19" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl4a.jpg",
	"20" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl5a.jpg",
	"21" : "https://ik.imagekit.io/mLsKqNSuB/post/live/ayanegradcer-a.jpg",
	"22" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive32a.jpg",
	"23" : "https://ik.imagekit.io/mLsKqNSuB/post/live/hinata4thomotenashikai1.jpg",
	"24" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230517-asukasotsucon1a.jpg",
	"25" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230518-asukasotsucon2a.jpg",
	"26" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive32a.jpg",
	"27" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230601-sakura3rdtourosaka2023a.jpg",
	"28" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutoue2016xebiosendaiday2a.jpg",
	"29" : "https://ik.imagekit.io/mLsKqNSuB/post/live/seiragradcer-a.jpg",
	"30" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023a.jpg",
	"31" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023g.jpg",
	"32" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023k.jpg",
	"33" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023o.jpg",
	"34" : "https://ik.imagekit.io/mLsKqNSuB/post/live/33rdunderlive-a.jpg",
	"35" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive33a.jpg",
	"36" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231112-shinzanmono-sakurazaka46a.jpg",
	"37" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231118-shinzanmono-hinatazaka46a.jpg",
	"38" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231127-shinzanmono-nogizaka46a.jpg",
	"39" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231130-shinzanmono-hinatazaka46a.jpg",
	"40" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231202-shinzanmono-sakurazaka46a.jpg",
	"41" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231203-shinzanmono-nogizaka46a.jpg",
	"42" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231219-bokuao-oneman-vol0a.jpg",
	"43" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl1a.jpg",
	"44" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl2a.jpg",
	"45" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl3a.jpg",
	"46" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl4a.jpg",
	"47" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive34a.jpg",
	"48" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zukkigradcerD1a.jpg",
	"49" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive35a.jpg",
	"50" : "https://ik.imagekit.io/mLsKqNSuB/post/live/saachangradcer-a.jpg",
	"51" : "https://ik.imagekit.io/mLsKqNSuB/post/live/bokuaonatsugasumi-a.jpg",
	"52" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d1a.jpg",
	"53" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d2a.jpg",
	"54" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d3a.jpg",
	"55" : "https://ik.imagekit.io/mLsKqNSuB/post/live/bokuao-aozorasummerfes2024a.jpg",
	"56" : "https://ik.imagekit.io/mLsKqNSuB/post/live/34thunderlive-a.jpg",
	"57" : "https://ik.imagekit.io/mLsKqNSuB/post/live/35thunderlive-a.jpg",
	"58" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive36a.jpg",
	"59" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive37a.jpg",
	"60" : "https://ik.imagekit.io/mLsKqNSuB/post/live/yodagradcon-a.jpg",
};
console.log(imageThumbA);

// =======================
// IMAGE THUMBNAIL B
// =======================

const imageThumbB = {
	"01" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogiskitslive2.jpg",
	"02" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive2021b.jpg",
	"03" : "https://ik.imagekit.io/mLsKqNSuB/post/live/jamexpo20-21b.jpg",
	"04" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive28b.jpg",
	"05" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive28b.jpg",
	"06" : "https://ik.imagekit.io/mLsKqNSuB/post/live/omitatekai2b.jpg",
	"07" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_10th-bdl2b.jpg",
	"08" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive29b.jpg",
	"09" : "https://ik.imagekit.io/mLsKqNSuB/post/live/kitanohinakogradconb.jpg",
	"10" : "https://ik.imagekit.io/mLsKqNSuB/post/live/tif2022nogizaka2.jpg",
	"11" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_1st-bdlb.jpg",
	"12" : "https://ik.imagekit.io/mLsKqNSuB/post/live/higuchinagradconb.jpg",
	"13" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive30b.jpg",
	"14" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutoue2019nagoyaday2b.jpg",
	"15" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive31b.jpg",
	"16" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl1b.jpg",
	"17" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl2b.jpg",
	"18" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl3b.jpg",
	"19" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl4b.jpg",
	"20" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl5b.jpg",
	"21" : "https://ik.imagekit.io/mLsKqNSuB/post/live/ayanegradcer-b.jpg",
	"22" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive32b.jpg",
	"23" : "https://ik.imagekit.io/mLsKqNSuB/post/live/hinata4thomotenashikai2.jpg",
	"24" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230517-asukasotsucon1b.jpg",
	"25" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230518-asukasotsucon2b.jpg",
	"26" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive32b.jpg",
	"27" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230601-sakura3rdtourosaka2023b.jpg",
	"28" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutoue2016xebiosendaiday2b.jpg",
	"29" : "https://ik.imagekit.io/mLsKqNSuB/post/live/seiragradcer-b.jpg",
	"30" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023b.jpg",
	"31" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023h.jpg",
	"32" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023l.jpg",
	"33" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023p.jpg",
	"34" : "https://ik.imagekit.io/mLsKqNSuB/post/live/33rdunderlive-b.jpg",
	"35" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive33b.jpg",
	"36" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231112-shinzanmono-sakurazaka46b.jpg",
	"37" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231118-shinzanmono-hinatazaka46b.jpg",
	"38" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231127-shinzanmono-nogizaka46b.jpg",
	"39" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231130-shinzanmono-hinatazaka46b.jpg",
	"40" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231202-shinzanmono-sakurazaka46b.jpg",
	"41" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231203-shinzanmono-nogizaka46b.jpg",
	"42" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231219-bokuao-oneman-vol0b.jpg",
	"43" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl1b.jpg",
	"44" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl2b.jpg",
	"45" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl3b.jpg",
	"46" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl4b.jpg",
	"47" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive34b.jpg",
	"48" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zukkigradcerD1b.jpg",
	"49" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive35b.jpg",
	"50" : "https://ik.imagekit.io/mLsKqNSuB/post/live/saachangradcer-b.jpg",
	"51" : "https://ik.imagekit.io/mLsKqNSuB/post/live/bokuaonatsugasumi-b.jpg",
	"52" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d1b.jpg",
	"53" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d2b.jpg",
	"54" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d3b.jpg",
	"55" : "https://ik.imagekit.io/mLsKqNSuB/post/live/bokuao-aozorasummerfes2024b.jpg",
	"56" : "https://ik.imagekit.io/mLsKqNSuB/post/live/34thunderlive-b.jpg",
	"57" : "https://ik.imagekit.io/mLsKqNSuB/post/live/35thunderlive-b.jpg",
	"58" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive36b.jpg",
	"59" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive37b.jpg",
	"60" : "https://ik.imagekit.io/mLsKqNSuB/post/live/yodagradcon-b.jpg",
};
console.log(imageThumbB);

// =======================
// IMAGE THUMBNAIL C
// =======================

const imageThumbC = {
	"01" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogiskitslive3.jpg",
	"02" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive2021c.jpg",
	"03" : "https://ik.imagekit.io/mLsKqNSuB/post/live/jamexpo20-21c.jpg",
	"04" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive28c.jpg",
	"05" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive28c.jpg",
	"06" : "https://ik.imagekit.io/mLsKqNSuB/post/live/omitatekai2c.jpg",
	"07" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_10th-bdl2c.jpg",
	"08" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive29c.jpg",
	"09" : "https://ik.imagekit.io/mLsKqNSuB/post/live/kitanohinakogradconc.jpg",
	"10" : "https://ik.imagekit.io/mLsKqNSuB/post/live/tif2022nogizaka3.jpg",
	"11" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_1st-bdlc.jpg",
	"12" : "https://ik.imagekit.io/mLsKqNSuB/post/live/higuchinagradconc.jpg",
	"13" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive30c.jpg",
	"14" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutoue2019nagoyaday2c.jpg",
	"15" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive31c.jpg",
	"16" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl1c.jpg",
	"17" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl2c.jpg",
	"18" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl3c.jpg",
	"19" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl4c.jpg",
	"20" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl5c.jpg",
	"21" : "https://ik.imagekit.io/mLsKqNSuB/post/live/ayanegradcer-c.jpg",
	"22" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive32c.jpg",
	"23" : "https://ik.imagekit.io/mLsKqNSuB/post/live/hinata4thomotenashikai3.jpg",
	"24" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230517-asukasotsucon1c.jpg",
	"25" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230518-asukasotsucon2c.jpg",
	"26" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive32c.jpg",
	"27" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230601-sakura3rdtourosaka2023c.jpg",
	"28" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutoue2016xebiosendaiday2c.jpg",
	"29" : "https://ik.imagekit.io/mLsKqNSuB/post/live/seiragradcer-c.jpg",
	"30" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023c.jpg",
	"31" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023i.jpg",
	"32" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023m.jpg",
	"33" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023q.jpg",
	"34" : "https://ik.imagekit.io/mLsKqNSuB/post/live/33rdunderlive-c.jpg",
	"35" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive33c.jpg",
	"36" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231112-shinzanmono-sakurazaka46c.jpg",
	"37" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231118-shinzanmono-hinatazaka46c.jpg",
	"38" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231127-shinzanmono-nogizaka46c.jpg",
	"39" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231130-shinzanmono-hinatazaka46c.jpg",
	"40" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231202-shinzanmono-sakurazaka46c.jpg",
	"41" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231203-shinzanmono-nogizaka46c.jpg",
	"42" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231219-bokuao-oneman-vol0c.jpg",
	"43" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl1c.jpg",
	"44" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl2c.jpg",
	"45" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl3c.jpg",
	"46" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl4c.jpg",
	"47" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive34c.jpg",
	"48" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zukkigradcerD1c.jpg",
	"49" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive35c.jpg",
	"50" : "https://ik.imagekit.io/mLsKqNSuB/post/live/saachangradcer-c.jpg",
	"51" : "https://ik.imagekit.io/mLsKqNSuB/post/live/bokuaonatsugasumi-c.jpg",
	"52" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d1c.jpg",
	"53" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d2c.jpg",
	"54" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d3c.jpg",
	"55" : "https://ik.imagekit.io/mLsKqNSuB/post/live/bokuao-aozorasummerfes2024c.jpg",
	"56" : "https://ik.imagekit.io/mLsKqNSuB/post/live/34thunderlive-c.jpg",
	"57" : "https://ik.imagekit.io/mLsKqNSuB/post/live/35thunderlive-c.jpg",
	"58" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive36c.jpg",
	"59" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive37c.jpg",
	"60" : "https://ik.imagekit.io/mLsKqNSuB/post/live/yodagradcon-c.jpg",
};
console.log(imageThumbC);

const imageThumbX = {
...imageThumbC,
};
console.log(imageThumbX);


// =======================
// IMAGE THUMBNAIL D
// =======================

const imageThumbD = {
	"01" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogiskitslive4.jpg",
	"02" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive2021d.jpg",
	"03" : "https://ik.imagekit.io/mLsKqNSuB/post/live/jamexpo20-21d.jpg",
	"04" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive28d.jpg",
	"05" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive28d.jpg",
	"06" : "https://ik.imagekit.io/mLsKqNSuB/post/live/omitatekai2d.jpg",
	"07" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_10th-bdl2d.jpg",
	"08" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive29d.jpg",
	"09" : "https://ik.imagekit.io/mLsKqNSuB/post/live/kitanohinakogradcond.jpg",
	"10" : "https://ik.imagekit.io/mLsKqNSuB/post/live/tif2022nogizaka4.jpg",
	"11" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_1st-bdld.jpg",
	"12" : "https://ik.imagekit.io/mLsKqNSuB/post/live/higuchinagradcond.jpg",
	"13" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive30d.jpg",
	"14" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutoue2019nagoyaday2d.jpg",
	"15" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive31d.jpg",
	"16" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl1d.jpg",
	"17" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl2d.jpg",
	"18" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl3d.jpg",
	"19" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl4d.jpg",
	"20" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_11th-bdl5d.jpg",
	"21" : "https://ik.imagekit.io/mLsKqNSuB/post/live/ayanegradcer-d.jpg",
	"22" : "https://ik.imagekit.io/mLsKqNSuB/post/live/underlive32d.jpg",
	"23" : "https://ik.imagekit.io/mLsKqNSuB/post/live/hinata4thomotenashikai4.jpg",
	"24" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230517-asukasotsucon1d.jpg",
	"25" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230518-asukasotsucon2d.jpg",
	"26" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive32d.jpg",
	"27" : "https://ik.imagekit.io/mLsKqNSuB/post/live/230601-sakura3rdtourosaka2023d.jpg",
	"28" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutoue2016xebiosendaiday2d.jpg",
	"29" : "https://ik.imagekit.io/mLsKqNSuB/post/live/seiragradcer-d.jpg",
	"30" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023d.jpg",
	"31" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023j.jpg",
	"32" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023n.jpg",
	"33" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2023r.jpg",
	"34" : "https://ik.imagekit.io/mLsKqNSuB/post/live/33rdunderlive-d.jpg",
	"35" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive33d.jpg",
	"36" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231112-shinzanmono-sakurazaka46d.jpg",
	"37" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231118-shinzanmono-hinatazaka46d.jpg",
	"38" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231127-shinzanmono-nogizaka46d.jpg",
	"39" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231130-shinzanmono-hinatazaka46d.jpg",
	"40" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231202-shinzanmono-sakurazaka46d.jpg",
	"41" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231203-shinzanmono-nogizaka46d.jpg",
	"42" : "https://ik.imagekit.io/mLsKqNSuB/post/live/231219-bokuao-oneman-vol0d.jpg",
	"43" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl1d.jpg",
	"44" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl2d.jpg",
	"45" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl3d.jpg",
	"46" : "https://ik.imagekit.io/mLsKqNSuB/post/live/nogizaka46_12th-bdl4d.jpg",
	"47" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive34d.jpg",
	"48" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zukkigradcerD1d.jpg",
	"49" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive35d.jpg",
	"50" : "https://ik.imagekit.io/mLsKqNSuB/post/live/saachangradcer-d.jpg",
	"51" : "https://ik.imagekit.io/mLsKqNSuB/post/live/bokuaonatsugasumi-d.jpg",
	"52" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d1d.jpg",
	"53" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d2d.jpg",
	"54" : "https://ik.imagekit.io/mLsKqNSuB/post/live/zenkokutour2024d3d.jpg",
	"55" : "https://ik.imagekit.io/mLsKqNSuB/post/live/bokuao-aozorasummerfes2024d.jpg",
	"56" : "https://ik.imagekit.io/mLsKqNSuB/post/live/34thunderlive-d.jpg",
	"57" : "https://ik.imagekit.io/mLsKqNSuB/post/live/35thunderlive-d.jpg",
	"58" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive36d.jpg",
	"59" : "https://ik.imagekit.io/mLsKqNSuB/post/live/minilive37d.jpg",
	"60" : "https://ik.imagekit.io/mLsKqNSuB/post/live/yodagradcon-d.jpg",
};
console.log(imageThumbD);


// =======================
// LINK HARDSUB
// =======================

const linkHardsub = {
	"01" : "",
	"02" : "",
	"03" : "https://lokerwfh.net/k3KMv0p",
	"04" : "",
	"05" : "https://lokerwfh.net/8bc8v",
	"06" : "",
	"07" : "",
	"08" : "https://lokerwfh.net/WJW0U",
	"09" : "",
	"10" : "https://lokerwfh.net/QSd7O",
	"11" : "",
	"12" : "",
	"13" : "https://lokerwfh.net/a80mz",
	"14" : "",
	"15" : "https://lokerwfh.net/cCm2R",
	"16" : "",
	"17" : "",
	"18" : "",
	"19" : "",
	"20" : "",
	"21" : "",
	"22" : "",
	"23" : "",
	"24" : "",
	"25" : "",
	"26" : "https://lokerwfh.net/uZwXKUT",
	"27" : "",
	"28" : "",
	"29" : "",
	"30" : "",
	"31" : "",
	"32" : "",
	"33" : "",
	"34" : "",
	"35" : "https://lokerwfh.net/GmwMWW4q",
	"36" : "",
	"37" : "",
	"38" : "",
	"39" : "",
	"40" : "",
	"41" : "",
	"42" : "https://lokerwfh.net/gDmU",
	"43" : "",
	"44" : "",
	"45" : "",
	"46" : "",
	"47" : "https://lokerwfh.net/CMFstnC",
	"48" : "",
	"49" : "https://sfl.gl/uTrde37B",
	"50" : "https://sfl.gl/u1qct",
	"51" : "https://sfl.gl/WuRi4z",
	"52" : "",
	"53" : "",
	"54" : "",
	"55" : "https://sfl.gl/qiRLOB8",
	"56" : "",
	"57" : "",
	"58" : "https://sfl.gl/dxNibg",
	"59" : "https://sfl.gl/TaHR8tuF",
	"60" : "",
};
console.log(linkHardsub);

// =======================
// LINK TRAKTEER
// =======================


const linkTrakteer = {
	"01" : "https://trakteer.id/moefangsubs/showcase/nogizaka-skits-live-oDTVw",
	"02" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-underlive-2021-miria-junna-graduation-vk0zb",
	"03" : "https://trakteer.id/moefangsubs/showcase/at-jam-expo-2020-2021-nogizaka46-4th-gen-softsub-kws7X",
	"04" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-28th-sg-underlive-2021-terada-ranze-graduation-NuLxz",
	"05" : "https://trakteer.id/moefangsubs/showcase/mini-live-28th-single-kimi-ni-shikarareta-tYnLr",
	"06" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-5th-gen-2nd-omitatekai-P1z04",
	"07" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-10th-birthday-live-day-2-412vk",
	"08" : "https://trakteer.id/moefangsubs/showcase/mini-live-29th-single-actually-MnqN5",
	"09" : "https://trakteer.id/moefangsubs/showcase/kitano-hinako-graduation-concert-softsub-hardsub-UGJFu",
	"10" : "https://trakteer.id/moefangsubs/showcase/220807-nogizaka46-5th-gen-at-tif-2022-sOyVD",
	"11" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-1st-birthday-live-XMghR",
	"12" : "https://trakteer.id/moefangsubs/showcase/higuchi-hina-graduation-ceremony-softsub-hardsub-WzYJT",
	"13" : "https://trakteer.id/moefangsubs/showcase/mini-live-30th-single-suki-to-iu-no-wa-rock-da-ze-kU4Mf",
	"14" : "https://trakteer.id/moefangsubs/showcase/190704-zenkoku-tour-2019-at-nagoya-dome-day-2-gwFAg",
	"15" : "https://trakteer.id/moefangsubs/showcase/mini-live-31st-single-koko-ni-wa-nai-mono-5CI4t",
	"16" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-11th-year-birthday-live-CyMPX",
	"17" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-11th-year-birthday-live-CyMPX",
	"18" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-11th-year-birthday-live-CyMPX",
	"19" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-11th-year-birthday-live-CyMPX",
	"20" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-11th-year-birthday-live-CyMPX",
	"21" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-suzuki-ayane-graduation-ceremony-epsde",
	"22" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-32nd-sg-underlive-day-2-enTTk",
	"23" : "https://trakteer.id/moefangsubs/showcase/hinatazaka46-4th-gen-omotenashikai-26AuA",
	"24" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-saito-asuka-graduation-concert-KkCAp",
	"25" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-saito-asuka-graduation-concert-KkCAp",
	"26" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-mini-live-32nd-single-hito-wa-yume-o-nido-miru-UiHPM",
	"27" : "https://trakteer.id/moefangsubs/showcase/230601-sakurazaka46-3rd-tour-2023-final-NwtUj",
	"28" : "https://trakteer.id/moefangsubs/showcase/160814-zenkoku-tour-2016-at-xebio-arena-day-2-day-performance-i7Bri",
	"29" : "https://trakteer.id/moefangsubs/showcase/230713-hayakawa-seira-graduation-ceremony-blKv5",
	"30" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-manatsu-no-zenkoku-tour-2023-at-jingu-WV6yr",
	"31" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-manatsu-no-zenkoku-tour-2023-at-jingu-WV6yr",
	"32" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-manatsu-no-zenkoku-tour-2023-at-jingu-WV6yr",
	"33" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-manatsu-no-zenkoku-tour-2023-at-jingu-WV6yr",
	"34" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-33rd-sg-underlive-HHa6o",
	"35" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-mini-live-33rd-single-ohitorisama-tengoku-lIP11",
	"36" : "https://trakteer.id/moefangsubs/showcase/shinzanmono-live-at-theater-milano-za-0rgQg",
	"37" : "https://trakteer.id/moefangsubs/showcase/shinzanmono-live-at-theater-milano-za-0rgQg",
	"38" : "https://trakteer.id/moefangsubs/showcase/shinzanmono-live-at-theater-milano-za-0rgQg",
	"39" : "https://trakteer.id/moefangsubs/showcase/shinzanmono-live-at-theater-milano-za-0rgQg",
	"40" : "https://trakteer.id/moefangsubs/showcase/shinzanmono-live-at-theater-milano-za-0rgQg",
	"41" : "https://trakteer.id/moefangsubs/showcase/shinzanmono-live-at-theater-milano-za-0rgQg",
	"42" : "https://trakteer.id/moefangsubs/showcase/231219-boku-ga-mitakatta-one-man-live-vol0-dgb5A",
	"43" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-12th-year-birthday-live-KPuiW",
	"44" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-12th-year-birthday-live-KPuiW",
	"45" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-12th-year-birthday-live-KPuiW",
	"46" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-12th-year-birthday-live-KPuiW",
	"47" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-mini-live-34th-single-monopoly-9aAeO",
	"48" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-yamashita-mizuki-graduation-concert-XLZ0d",
	"49" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-mini-live-35th-single-chance-wa-byoudou-0Tn3e",
	"50" : "https://trakteer.id/moefangsubs/showcase/240819-kakehashi-sayaka-graduation-ceremony-kcDI3",
	"51" : "https://trakteer.id/moefangsubs/showcase/boku-ga-mitakatta-aozora-natsugasumi-YFKf8",
	"52" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-manatsu-no-zenkoku-tour-2024-in-tokyo-at-meiji-jingu-stadium-2DXIz",
	"53" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-manatsu-no-zenkoku-tour-2024-in-tokyo-at-meiji-jingu-stadium-2DXIz",
	"54" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-manatsu-no-zenkoku-tour-2024-in-tokyo-at-meiji-jingu-stadium-2DXIz",
	"55" : "https://trakteer.id/moefangsubs/showcase/boku-ga-mitakatta-aozora-aozora-summer-festival-2024-Jrur9",
	"56" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-34th-sg-underlive-S4tM5",
	"57" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-35th-sg-underlive-A8xgQ",
	"58" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-mini-live-36th-single-cheat-day-jXHba",
	"59" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-mini-live-37th-single-hodoukyou-Q8S8Y",
	"60" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-yoda-yuuki-graduation-concert-zYNOs",
};
console.log(linkTrakteer);


// =======================
// FILE PASSWORD
// =======================

const filePassword = {
	"01" : "(tidak ada password)",
	"02" : "(tidak ada password)",
	"03" : "jamexpo20202021",
	"04" : "(tidak ada password)",
	"05" : "(tidak ada password)",
	"06" : "(tidak ada password)",
	"07" : "(tidak ada password)",
	"08" : "(tidak ada password)",
	"09" : "(tidak ada password)",
	"10" : "satsukicenter!omedetou!",
	"11" : "(tidak ada password)",
	"12" : "(tidak ada password)",
	"13" : "(tidak ada password)",
	"14" : "(tidak ada password)",
	"15" : "(tidak ada password)",
	"16" : "(tidak ada password)",
	"17" : "(tidak ada password)",
	"18" : "(tidak ada password)",
	"19" : "(tidak ada password)",
	"20" : "(tidak ada password)",
	"21" : "(tidak ada password)",
	"22" : "(tidak ada password)",
	"23" : "(tidak ada password)",
	"24" : "(tidak ada password)",
	"25" : "(tidak ada password)",
	"26" : "(tidak ada password)",
	"27" : "(tidak ada password)",
	"28" : "(tidak ada password)",
	"29" : "(tidak ada password)",
	"30" : "(tidak ada password)",
	"31" : "(tidak ada password)",
	"32" : "(tidak ada password)",
	"33" : "(tidak ada password)",
	"34" : "(tidak ada password)",
	"35" : "(tidak ada password)",
	"36" : "(tidak ada password)",
	"37" : "(tidak ada password)",
	"38" : "(tidak ada password)",
	"39" : "(tidak ada password)",
	"40" : "(tidak ada password)",
	"41" : "(tidak ada password)",
	"42" : "BokuNoKamihikoukiTobanakatta",
	"43" : "(tidak ada password)",
	"44" : "(tidak ada password)",
	"45" : "(tidak ada password)",
	"46" : "(tidak ada password)",
	"47" : "(tidak ada password)",
	"48" : "(tidak ada password)",
	"49" : "(tidak ada password)",
	"50" : "Saachan!Arigatou!SaachanNoMiraiNiSachiare",
	"51" : "SelamatUlangTahunLangitBiru",
	"52" : "(tidak ada password)",
	"53" : "(tidak ada password)",
	"54" : "(tidak ada password)",
	"55" : "BokuAo!TsuyokuNiNarou!",
	"56" : "(tidak ada password)",
	"57" : "(tidak ada password)",
	"58" : "(tidak ada password)",
	"59" : "(tidak ada password)",
	"60" : "(tidak ada password)",
};
console.log(filePassword);

// =======================
// BAHASA SUB
// =======================

const subLanguage = {};
for (let i = 1; i <= 9999; i++) {
  subLanguage[i.toString().padStart(2, '0')] = "Bahasa Indonesia";
}
console.log(subLanguage);