const acaraData = {
    nogizakaskitsact1: "Nogizaka Skits merupakan acara variety show menggantikan 'Nogizaka Doko e' sebagai acara utama Nogizaka46 gen-4. Acara ini masih bersama komedian Saraba Seishun no Hikari, yaitu Morita dan Higashi Bukuro. Mereka berdua juga turut ikut berperan dalam berbagai sketsa komedi.",
    nogizakaskitsact2: "Nogizaka Skits ACT 2 merupakan acara variety show meneruskan season pertamanya, dimana tidak hanya gen-4 yang berpartisipasi, tapi juga senpai gen-3 ikut berpartisipasi. Acara ini masih bersama komedian Saraba Seishun no Hikari, yaitu Morita dan Higashi Bukuro. Mereka berdua juga turut ikut berperan dalam berbagai sketsa komedi.",
    nogistartanjou1: "Setelah selesainya Nogizaka Skits ACT 2, kini para member generasi ke-4 punya acara yang baru, yang berjudul Nogizaka Star Tanjou. Adalah sebuah acara dimana para member akan ditantang untuk menyanyikan lagu-lagu era Showa dan Heisei, bersama dengan MC dari komedian Pekopa.",
    nogistartanjou2: "Setelah sukses dengan season pertamanya, Nogizaka Star Tanjou kembali hadir di season 2. Masih bersama komedian Pekopa sebagai MC, dan kali ini para member senpai dari gen-1, gen-2, dan gen-3 ikut tampil dan memeriahkan acara ini.",
    shinnogistar: "\"Shin Nogizaka Star Tanjou!\" merupakan acara pembaruan dari seri sebelumnya, dimana pemain utamanya bukan gen-4 lagi melainkan gen-5 yang baru bergabung. Bersama MC komedian Oswald, kita akan melihat pertumbuhan mereka baik cara mereka bernyanyi, maupun beradaptasi dengan grup.",
    chounogistar: "\"Chou Nogizaka Star Tanjou!\" merupakan season keempat dari Nogizaka Star Tanjou. Kembali bersama gen-5 dan MC komedian Oswald, tidak hanya menyanyikan lagu-lagu populer era Showa dan Heisei, namun juga mereka untuk pertama kalinya menantang diri dalam berakting di sketsa komedi dengan nama segmen Nogista Skits.",
    nogiotameshichuu: "\"Nogizaka Otameshichuu\" merupakan variety show para member Under. Slot acara ini menggantikan variety sebelumnya, Nogi Eigo. Di awal episode hingga episode 10, pembawa acaranya adalah dari gen-2, Terada Ranze. Karena memutuskan lulus, episode setelahnya dibawakan oleh Ito Riria dari gen-3. MC ini didampingi partnernya dari seorang komedian Suzuki Taku. Variety ini akan mencoba berbagai tantangan secara acak.",
    hinachoi: "\"Hinatazaka46 desu. Chotto Ii desu ka?\" merupakan variety show para member Hinatazaka46. Mereka bertindak sebagai reporter, dan setiap kali mereka mewawancarai para artis papan atas tanpa NG, dan mencoba untuk menonjolkan sisi tak terduga dan pesona tersembunyi mereka.",
    sakurameets: "\"Sakura Meets?\" merupakan acara variety dari Barabara Daisakusen untuk member Sakurazaka46. Isinya para member akan menantang sketsa komedi dan berkolaborasi dengan komedian-komedian Jepang.",
	kyoccorohee: "\"Kyoccorohee\" merupakan acara variety di mana Saito Kyoko dan Hikorohi, yang dikenal karena suara mereka yang bernada rendah, mendalami pesona tarian, namun di tengah-tengah acara, konsepnya berubah menjadi \"Midnight Weird Talk Variety\"",
    nogizakaohatsu: "\"Nogizaka46 Yamazaki Rena to Ohatsu-chan\" merupakan acara dimana Yamazaki Rena dari gen-2 menjadi MC, dan para member Nogizaka46 akan mencoba pengalaman pertama mereka yang telah lama ditunggu-tunggu dan diinginkan (ohatsu)!",
	nogiromance: "Garapan santai kali ini datang dari koleksi lama, tahun 2012. Nogizaka Roman atau Nogizaka Romance adalah semacam \"visualisasi\" cerita dari para novelis dan penulis terkenal, yang lalu dimainkan oleh member-member Nogizaka46. Kalau kalian menyukai sastra tidak ada salahnya menonton ini.",
	nogikoujichuu: "\"Nogizaka Under Construction\" atau \"Nogizaka Koujichuu\" merupakan acara variety show dari Nogizaka46 dengan MC duo komedian Bananaman. Acara ini bisa dibilang kelanjutan dari acara sebelumnya, yaitu \"Nogizaka tte, Doko\?\" yang tayang di stasiun TV yang sama, TV Tokyo pada hari minggu pukul 24:00-24:30 JST. Setiap minggunya pada awalnya, satu member dipilih untuk mempresentasikan program yang ingin dia lakukan. Dibandingkan dengan \"Nogizaka tte, Doko\?\", dimana setiap member sebagai protagonis project, yang akan lebih menunjukkan karakteristik dan pesona masing-masing member. Namun tipe seperti itu dibatalkan setelah ep25.",
	nogibingo: "\"NOGIBINGO!\" adalah program yang menguji apakah Nogizaka46 bisa menjadi grup idola nasional jika mereka melakukan persis seperti yang dilakukan AKB48 dengan AKBINGO!-nya.",
	nogizakashow: "Sebuah acara dari induknya AKB48SHOW, merupakan acara yang mencakup penampilan live di studio, wawancara, percakapan, sketsa, liputan lokasi, dan dokumenter yang memperkenalkan pesona para member dari berbagai sudut kepada penggemar. Untuk NOGIZAKA46 SHOW! sendiri dimulai dari 1 Maret 2014, dimana merupakan saingan resmi AKB48, memiliki acara terpisah yang disebut 'Bessatsu Nogizaka46 SHOW!' yang ditayangkan secara tidak teratur.",
	nogipasokon: "\"Tokyo Pasokon Club\" merupakan acara para member Nogizaka46 untuk mempelajari tentang bahasa pemograman khususnya membuat sebuah game dari awal.",
	nantebida: "\"Kotoge Eiji no Nante Bi da!\" merupakan acara dengan tagline 'Bahkan bagi pemula pun bisa mudah belajar tentang seni, sebuah acara variety seni paling mudah di akses di Jepang'.",
	koukouseiquiz: "Sebuah turnamen yang disponsori Nippon Television dan diadakan setiap musim panas.",
	hamasukahousoubu: "Hamasuka Housou-bu merupakan acara bincang-bincang mengenai musik yang disiarkan di TV Asahi dari 8 Oktober 2021. Acara ini dipandu oleh Okamoto Hama (OKAMOTO'S) dan Saito Asuka.",
	spicysessions: "Spicy Sessions adalah program musik baru dari TBS Channel yang wajib ditonton para pecinta musik, menampilkan sesi \"menggugah selera\" bersama tamu istimewa. Dipandu oleh Kurosawa Kaoru dari Gospellers sebagai MC utama, setiap episode menghadirkan satu tamu musisi ternama untuk berkolaborasi dalam penampilan live, sesi improvisasi dengan band studio, dan diskusi mendalam tentang akar musik mereka. Program ini juga menampilkan Nakanishi Aruno dari Nogizaka46 sebagai co-host yang turut menyumbangkan suara vokalnya. Sebagai bonus unik, di segmen akhir, Kurosawa yang pencinta kari memperkenalkan hidangan kari lezat pilihannya sambil mengobrol santai.",
	// ------------
	// ------------
	// ------------
	nogidougaAsobudake: "\"Nogizaka Asobu dake\" merupakan acara khusus yang disiarkan dalam platform Nogi Douga. Dalam acara ini, para member (2-3 lebih member dalam satu episode) melakukan hal senang-senang, seperti pergi ke tempat arena hiburan, restoran, dan lain sebagainya.",
	nogidougaKubochannel: "\"Kubo Channel\" merupakan acara khusus yang disiarkan dalam platform Nogi Douga yang dibuat di mana konten-konten di dalamnya dijelaskan oleh Kubo Shiori, yang memiliki kecintaan terbesar pada grup Nogizaka46 dan memiliki ingatan yang kuat. Program ini baik konser, MV maupun konten lainnya membuat yang menonton menjadi lebih menarik, dengan cerita di balik layar dari sudut pandang para member.",
	nogidougaDekirumon: "\"Hitori de Dekirumon\" merupakan acara khusus yang disiarkan dalam platform Nogi Douga dimana para member gen-5 Nogizaka46 menantang berbagai hal dengan sendirian saja sambil memutar kamera yang juga sendirian.",
    nogidougaBurari: "\"Nogizaka Burari\" merupakan konten dari Nogi Douga di mana satu member dari Nogizaka46 diminta untuk merancang \"Jika menghabiskan liburan bersama member, apa yang akan dilakukan, dengan siapa, dan di mana?\" sebagai tema. Mereka akan menghabiskan hari libur sesuai dengan rencana ideal mereka sambil mengambil foto selfie, dan konten ini akan memberikan gambaran tentang pengalaman tersebut.",
	kaettekitayakubochannel: "Kaettekita! Yakubo Channel, merupakan season kedua dari seri Yakubo Channel dengan MC Yakubo Mio dan kameramen Hayashi Runa dari gen-4 yang berisi konten segmen ulasan makanan para member gen-5 saat Manatsu no Zenkoku Tour 2024.",
	
	// ------------
	// ------------
	// ------------
	gourmetSakamichi: "\"Gurume no Sakamichi\" adalah program di mana member Nogizaka46 menjelajahi lebih dari 1000 restoran setiap tahun yang direkomendasikan oleh Forin Debu Hasshi untuk menikmati 'hidangan yang harus dimakan sekarang.'",
	yakubonoheya: "\"Yakubo no Heya\" adalah acara resmi Nogi Fractal yang dibawakan oleh Yakubo Mio, supporter resmi Nogi Fractal. Siarannya selalu diadakan di NogiFra Official X (Twitter) sebulan sekali.",
	linelive: "Di LINE LIVE, ada program yang disiarkan berjudul \"Nogizaka46・Kubo Shiori no Nogizaka Noborizaka\", yang menampilkan Kubo Shiori dari Nogizaka46. Sayangnya, LINE LIVE menghentikan layanannyapada 31 Maret 2023.",
	kokushokokusan: "Ini adalah program YouTube di mana member Nogizaka46 mengunjungi lokasi produksi pertanian dan berbagi daya tarik 'pangan dan pertanian' melalui pengalaman seperti bercocok tanam dan memanen. Dalam episodenya, JA Group mendistribusikan video di mana member Nogizaka46 melaporkan kinerja para petani, JA, dll., berdasarkan tiga tema yaitu 'pertanian perkotaan', 'pertanian baru', dan 'pertanian cerdas'.",
	hinatazakachannel: "Hinatazaka Channel merupakan channel resmi YouTube kedua dari Hinatazaka46. Dibuka pada tanggal 19 April 2023, dengan siaran langsung peresmian yang juga diadakan pada hari yang sama. Di sini, mereka menyajikan berbagai konten asli yang hanya bisa dilihat di sini.",
	hinasanpoinyokohama: "\"Hina Sanpo in Yokohama\" adalah konten yang diunggah ke situs web khusus dalam rangka merayakan ulang tahun ke-4 debut Hinatazaka46 melalui \"4kaime no Hinatansai\". Konten ini diunggah untuk rute member gen-1 pada 24 Maret 2023, dan untuk rute member gen-2 pada 25 Maret 2023. Rute \"Hina Sanpo in Yokohama\" mencakup landmark seperti Yokohama Landmark Tower, Yokohama Cosmo World, Yokohama Red Brick Warehouse, Yokohama Customs, Gedung Kantor Pusat Pemerintah Prefektur Kanagawa, Taman Yamashita, dan Stadion Yokohama.",
	mtv: "MTV Unplugged adalah seri musik yang ditayangkan MTV, menampilkan musisi terkenal memainkan alat musik akustik.",
	nogi46hour2022: "Untuk merayakan ulang tahunnya yang ke-10, Nogizaka46 mengadakan program internet \"Nogizaka 46 Jikan TV\" selama 46 jam dari 21 Februari pukul 19:00 hingga 23 Februari pukul 17:00. Untuk tahun 2022, acara ini disiarkan di YouTube. Salah satu segmen mereka adalah menampilkan segmen \"Nogizaka Denshidai\" di mana setiap member memproduksi segmen sekitar 10 menit, dan acara populer seperti \"Jinro Midnight\" di mana member berpakaian piyama bermain permainan menebak siapa yang menjadi serigala.",
	kichijoujiwalkers: "\"Kichijoji Walkers\" adalah proyek khusus terkait dengan drama TV \"Kichijoji Losers\" yang disiarkan di TV Tokyo. Dalam proyek ini menjelajahi lokasi syuting, toko terkenal, dan tempat-tempat tidak diketahui di Kichijoji yang muncul dalam drama. Sebagai support role dalam drama Kichijoji Losers, Iwamoto Renka dan Tashima Meru (HKT48) mendapatkan project khusus untuk mereview daerah Kichijoji. Kichijoji merupakan sebuah daerah di kota Musashino di Tokyo. Daerah ini populer dengan berbagai toko, restoran, bar, dan kedai kopi.",
	minnanomameo: "\"Minna no Mameo\" adalah short anime yang dikonsepkan oleh Nibu Akari dari Hinatazaka46. Anime ini mulai tayang sejak April 2022 di acara varietas TV Asahi 'Onegai! Ranking presents Sodaterebi' dan Nibu Akari juga berperan sebagai pengisi suara. Acara ini lahir dari variety \"Manga Michi\". di mana seorang tokoh terkenal menyusun cerita yang kemudian diilustrasikan oleh seorang mangaka menjadi satu manga. Ini adalah cerita tentang Mameo, anjing Shiba Inu dengan kepribadian buruk, dan merupakan manga pertarungan anjing dan pemilik dari Mameo bisa mendengar suara anjingnya.",
	// // ------------
	// // ------------
	// // ------------
	single20tabisuru: "Sebuah bonus dari single ke-20 bernama \"Nogizaka Tabisuru 3-nin\" di mana tiga member Nogizaka46 membentuk tim dan mengunjungi berbagai tempat di seluruh Jepang. Para member ini sendiri yang menentukan rute perjalanan dan tempat makan selama perjalanan mereka.",
	single24doc: "Di single ke-24, \"Yoake made Tsuyogaranakutemo Ii\" menyertakan dokumenter tiap generasi sebagai konten bonus pada DVD.",
	single26pv: "Single ke-26 \"Boku wa Boku o Suki ni Naru\" mencakup PV untuk semua 16 member gen-4. PV individu ini termasuk dalam edisi terbatas (CD+Blu-ray) dari Type-A hingga Type-D, yang dirilis pada 27 Januari 2021.",
	single27pv: "Single ke-27 \"Gomenne Fingers crossed\" mencakup PV untuk semua member Nogizaka46. PV individu ini termasuk dalam edisi terbatas (CD+Blu-ray) dari Type-A hingga Type-D.",
	single28doc: "Single ke-28 \"Kimi ni Shikarareta\" yang dirilis pada 22 September 2021 ini mencakup 3 dokumenter para member yang lulus, antara lain Terada Ranze, Takayama Kazumi, dan Ozono Momoko. Juga satu video pembuatan/making of pembuatan MV di single ini.",
	single29doc: "Single ke-29 \"Actually\" memuat film dokumenter tentang gen-5 yang baru bergabung yang dirilis pada 23 Maret 2022. Selain itu, dalam Nogizaka Haishinchuu, terdapat satu dokumenter dari Kawasaki Sakura.",
	single30pv: "Single ke-30 \"Suki to Iu no wa Rock daze!\" merilis 2 versi bonusnya, yaitu PV dari gen-5 dan juga lagu-lagu pilihan dalam Manatsu no Zenkoku Tour 2021, terbagi menjadi beberapa section.",
	single30zenkoku: "Single ke-30 \"Suki to Iu no wa Rock daze!\" merilis 2 versi bonusnya, yaitu PV dari gen-5 dan juga lagu-lagu pilihan dalam Manatsu no Zenkoku Tour 2021, terbagi menjadi beberapa section.",
	single31zenkoku: "Single ke-31 \"Koko ni wa nai mono\" merilis lagu-lagu pilihan dalam Manatsu no Zenkoku Tour 2022 di Meiji Jingu Stadium.",
	single32pv: "Single ke-32 \"Hito wa Yume wo Nido Miru\" yang dirilis pada 29 Maret 2023 merilis PV untuk gen-5, dan 31st Single Under Live beserta before & after selama konsernya.",
	single32under: "Single ke-32 \"Hito wa Yume wo Nido Miru\" yang dirilis pada 29 Maret 2023 merilis PV untuk gen-5, dan 31st Single Under Live beserta before & after selama konsernya.",
	single33pv: "Single ke-33 \"Ohitorisama Tengoku\" yang dirilis pada 23 Agustus 2023 ini sama seperti sebelumnya, yaitu merilis PV untuk gen-5, dan 32nd Single Under Live.",
	single33under: "Single ke-33 \"Ohitorisama Tengoku\" yang dirilis pada 23 Agustus 2023 ini sama seperti sebelumnya, yaitu merilis PV untuk gen-5, dan 32nd Single Under Live.",
	single34zenkoku: "Single ke-34 \"Monopoly\" yang dirilis pada 6 Desember 2023 ini hanya merilis pilihan lagu-lagu dari Manatsu no Zenkoku Tour 2023 di Okinawa.",
	single35: "Single ke-35 \"Chance wa Byoudou\" yang dirilis pada 10 April 2024 ini merilis menyertakan rekaman video live \"Shinsanmono LIVE at THEATER MILANO-Za\" baik yang offline maupun yang pernah di-streaming pada saat itu. Bonus video ini mencakup penampilan sebagian lagu yang dipentaskan bersama dengan rekaman penampilan dari semua 11 member \"Ohitorisama Tengoku Project\" yang menampilkan member yang berbeda dalam setiap pertunjukan.",
	single36: "Single ke-36 \"Cheat Day\" yang dirilis pada 21 Agustus 2024 merilis 35th Single Under Live beserta interview pada member Under yang pertama kalinya hanya ada gen-4 dan gen-5 saja.",
	single37: "Single ke-37 \"Hodoukyou\" yang dirilis pada 11 Agustus	2024 merilis video perjalanan mereka saat konser di Hong Kong pada beberapa waktu yang lalu. Dimulai dari keberangkatan, berbagai penampilan, latihan para member untuk ingin menyapa fansnya dengan bahasa Kanton, dan berbagai cerita lainnya.",
	timeflies: "Dalam koleksi ini dirilis juga 'Nogizaka46 10th Anniversary Documentary Movie \"10nen no Ayumi\"', sebuah video berdurasi panjang yang berisi perjalanan sejarah Nogizaka46 dari awal dibentuk hingga saat Best Album ini dirilis.",
	hinatasingle2: "Dalam single ke-2 'Doremisolasido', para member Hinatazaka46 mencoba berbagai hal untuk pertama kalinya. Terdapat 6 judul dan masing-masing member berkelompok.",
	// // ------------
	// // ------------
	// // ------------
	nogikoiMousouJoshi: "Nogikoi Mousou Joshi Koi o Kataru ini adalah seri dari Nogikoi pada Januari 2018 lalu. Disini yang akan bertindak adalah Saito Asuka, Hori Miona dan Yoda Yuuki, dengan setiap episodenya memiliki cerita-cerita yang berbeda.",
	nogikoiMousouShoujo: "Nogikoi Mousou Shoujo Koi o Kataru ini adalah event dari Nogikoi pada Maret 2018 lalu. Disini yang akan bertindak adalah Yamashita Mizuki, Kubo Shiori dan Ozono Momoko, dengan setiap episodenya memiliki cerita-cerita yang berbeda.",
	nogikoiCafe: "Kali ini adalah garapan Nogikoi Cafe 7th Stories yang rilis pada Mei 2018. Ya, digarap karena short drama cuma 3-4 menitan. Tiap episode berbeda cerita dan berbeda member yang ikut serta. ",
	nogikoiNatsunoKoe: "\"Kono Koe, Kimi ni Todoketai\" merupakan event dari Nogikoi pada bulan Juli 2018, dengan partisipasi 3 member Nogizaka46, yaitu Hoshino Minami, Kitano Hinako dan Iori Sagara.",
	nogikoiItsukaDokokade: "Aplikasi game resmi Nogizaka46 \"Nogikoi\" menghadirkan event \"Itsuka doko ka de ~Hello Again~\" mulai pukul 15:00 pada tanggal 10 Desember 2018. Konsep dari seri ini adalah \"perpisahan dan reuni\" dimana sang perempuan telah menjadi tumbuh dewasa. Dalam aplikasinya, untuk Nanase maupun Wakatsuki terdiri dari 8 episode dan 1 video ending. Nah, yang dibagikan disini adalah video endingnya.",
	nogikoiAshitamo: "Nogikoi kali ini berformat multi-ending, di mana akhir cerita berubah berdasarkan pilihan pengguna. Video ini juga mencakup dua ending. Dengan tema 'Pilihan Takdir dan Pertemuan', video ini diproduksi dengan pengaturan dan kostum yang tidak dapat ditemui di tempat lain, dengan keterlibatan Shiraishi dan Ikuta.",
	nogikoiEnjiruGirls: "Dalam aplikasi game smartphone Nogizaka46 \"Nogikoi ~sakamichi no shita de, ano hi boku wa koi o shita ~\" pada 10 Oktober 2019 mengadakan event \"Enjiru Girls! -Bibop Gekiken\". Dibintangi oleh member gen-4, yaitu Endo Sakura, Kaki Haruka dan Tsutsui Ayame. Menghadirkan episode 0 hingga 3 yang semuanya berkaitan dengan jalan cerita.",
	nogikoiGoodbyeEnsemble: "Nogikoi tahun 2020 merilis event \"Goodbye Ensemble\". Dengan 3 episode dibintangi oleh Shiraishi Mai, Akimoto Manatsu, Takayama Kazumi dan Matsumura Sayuri. Plot ceritanya menggambarkan kerinduan Maiyan pada teman-temannya saat mengunjungi sebuah toko tempat mereka biasa berkumpul",
	nogikoi5byougo: "Dalam perayaan The 5th Anniversary Campaign, pada 31 Maret-4 April 2021 diadakan event \"5byougo, Kimi o Suki ni naru\". Dibintangi oleh member baru gen-4, yaitu Hayashi Runa, Matsuo Miyu, Kuromi Haruka, Sato Rika dan Yumiki Nao.",
	nogikoiNounaiAngels: "Nogikoi di 20 Oktober 2021 merilis drama original \"Nounai Angels\" dengan total 5 episode pada channel YouTube resminya. Drama ini dibintangi oleh Saito Asuka, Hoshino Minami, Yamashita Mizuki dan Endo Sakura. Ceritanya menggambarkan 4 malaikat berkepribadian beda-beda dalam diri seseorang yang dipanggil 'kamu'.",
	nogikoiMattaSukitte: "Nogikoi di 13 April 2022 merilis seri barunya berjudul \"Mata Sukitte Iwanakucha\" pada channel YouTube resminya. Drama ini dibintangi oleh Kubo Shiori, Umezawa Minami, Kaki Haruka dan Hayakawa Seira. Di Nogikoi ini mengisahkan tentang empat orang yang tidak memiliki pengalaman cinta dan setiap hari berkumpul di kafe yang sama sejak masa sekolah menengah.",
	nogikoiKokuhakuno1byoumae: "\"Kokuhaku no Ichibyou mae\" merupakan event dari Nogikoi tahun 2022 dimana yang berpartisipasinya hanya member baru, yaitu gen-5. Yang kami share disini adalah hanya bagian movie 1 dan 2. Member gen-5 ada 11 orang jadi di dalamnya ada 22 video.",
	nogikoi3toubun: "'3-bun no Valentine' adalah short drama yang dibintangi oleh Iwamoto Renka, Endo Sakura, dan Yoda Yuki. Mulai tanggal 20 Januari 2023, drama ini disiarkan melalui Nogikoi. Bagian pertama di-premier-kan di saluran YouTube resminya, sedangkan bagian kedua dapat diakses secara gratis melalui aplikasinya.",
	hinakoifilms: "Untuk merayakan ulang tahun pertama HINAKOI, project \"HINAKOI FILMS 'Kimi to Boku no, Hinata no Hatsukoi'\" telah diluncurkan. Project ini diatur dalam setting yang sama dengan permainan, SMA Hinatazaka, di mana member Hinatazaka46 muncul sebagai teman sekelas dan adik kelas karakter utama. Yang pertama ini, \"Kimi to Boku no Hinata no Hatsukoi - Bunkasai Matsuri Magic wa Totsuzen ni Hen -\" menampilkan Kageyama Yuuka, Takamoto Ayaka, Kawata Hina, Tomita Suzuka, Matsuda Konoka, dan Miyata Manamo. Film pendek empat episode menggambarkan awal dari hubungan cinta selama persiapan untuk Hinakosai, festival budaya yang diadakan di SMA Hinatazaka.",
	// // ------------
	// // ------------
	// // ------------
	saishowapaa: "Tonegawa Gota adalah putra pertama dari seorang politisi terkenal. Sejak kecil, dia tidak memiliki apapun yang dia inginkan dan dia hanya mengikuti ayahnya. Ayahnya ingin Tonegawa Gota menjadi seorang politisi seperti dirinya, tetapi, Tonegawa Gota memutuskan untuk mendaftar di pusat pelatihan komedian. Di sana, ia membentuk duo komedi dengan Sawamura Ginpei, yang tidak banyak bicara tentang dirinya sendiri.",
	lovesharing: "\"Jadikan kami bertiga sebagai pacarmu\" Hubungan bersama yang belum pernah terjadi sebelumnya dengan tiga gadis cantik sekolah, Yui (Nakamura Reno), Wakana (Mukai Hazuki), dan Midori (Yumiki Nao), telah dimulai. Di balik berbagi cinta yang aneh ini, ada rahasia yang mengejutkan.",
	actress: "5 tahun telah berlalu sejak insiden di cafe Dominand. Serangkaian insiden telah terjadi yang meniru novel \"Escape Beyond\", yang diterbitkan oleh aktris populer Mase Kanna, dan telah menjadi perbincangan di seluruh kota",
	koshodomonogatari: "Berlatar di sebuah toko buku tua tertentu bernama \"Yume Neko\", ketika para gadis yang berkunjung di sana mulai membaca sebuah novel misteri yang direkomendasikan oleh pemilik toko, mereka melakukan perjalanan kembali ke masa lalu ke dunia novel, di mana kekejaman terungkap. Ini juga menggambarkan pertumbuhan seorang gadis yang menemukan jawaban atas masalah dan konflik yang dialami gadis-gadis dalam kehidupan nyata dengan berinteraksi dengan orang-orang yang mereka temui di dunia novel yang tergelincir kembali ke masa lalu.",
	doityourself: "Revolusi Industri IV telah mengarah pada perkembangan teknologi canggih yang dengan cepat mengubah dunia. Akibatnya, sekolah-sekolah telah mulai menggabungkan teknologi-teknologi ini ke dalam kurikulum mereka, meninggalkan cara-cara lama. Salah satu institusi seperti itu adalah Sekolah Khusus Putri Yuyu yang elit, tempat Serufu Yua dan sahabat masa kecilnya, Miku \"Purin\" Suride, telah mendaftar. Meskipun Purin yang menguasai teknologi diterima di Sekolah Tinggi Yuyu, Serufu yang sering mengalami kemalangan ditolak dan masuk ke SMA Putri Gatagata yang lebih tradisional, yang membuat persahabatan mereka retak.",
	truckgirl: "Kehidupan sehari-hari dari sopir truk muda, Kurate Jun, yang bekerja di industri logistik truk yang didominasi oleh pria. Dia menjalani hari-harinya dengan penuh semangat, dan menikmati minum-minuman setelah bekerja untuk menghilangkan kelelahannya.",
	rakujitsu: "Kaori Hasebe adalah seorang sutradara film pemula. Dia berkonsultasi dengan penulis naskah baru, Mahiro Kai, tentang skenario filmnya. Naskahnya berdasarkan pada Kasus Pembunuhan Keluarga Sasazuka-cho yang terjadi 15 tahun lalu. Kasus pembunuhan itu melibatkan seorang pria hikikomori yang membunuh adik perempuannya di rumahnya dan kemudian membakar rumahnya. Kebakaran itu juga menewaskan orang tuanya.",
	hikkoshitantei: "Tendo Sakura adalah seorang pekerja baru yang akan mulai bekerja di toko buku. Dia lebih menyukai novel misteri dan teka-teki daripada makan 3 kali sehari. Ketika masih SMA, dia mendirikan klub penelitian misteri, tetapi karena sifatnya yang pendiam, hanya ada satu anggota di klub tersebut. Dalam hidupnya, tidak pernah ada satu pun insiden yang terjadi, sehingga setiap hari terasa membosankan baginya. Namun, seiring dengan memulai hidup baru dan tinggal sendiri sebelum memulai hidup baru, Sakura, sambil merasa gugup, sedang bersiap-siap untuk menyapa tetangga, tiba-tiba terdengar jeritan seorang wanita. Tanpa disangka, dia terlibat dalam sebuah insiden. Apa insiden yang dia alami? Barisan teka-teki aneh yang tiba-tiba datang... Apakah itu kode? Atau pesan? Teka-teki yang dia impikan bahkan dalam mimpinya kini dimulai!",
	sonnakazoku: "Ichika, gadis SMA yang hobi game kuis, hidup dalam keluarga dengan aturan aneh. Ayahnya, Reitaro, dilarang melewati selotip yang dipasang di seluruh rumah oleh ibunya, Kazumi. Orang tua Ichika tidak pernah berbicara satu sama lain, dan Reitaro harus hidup terpisah dalam kesendirian.",
	mirainowatashi: "Igarashi Raito, seorang pegawai kantor pemerintah yang telah bekerja selama 10 tahun, hidup di bawah tekanan untuk \"tidak boleh gagal\" dalam masyarakat yang penuh risiko, di mana satu langkah kecil bisa berujung pada bencana besar. Selama ini, Raito menjalani hidup yang aman dan stabil. Namun, tiba-tiba muncul seorang pria tua yang mengaku sebagai \"Igarashi Raito dari masa depan.\" Dengan pandangan hidup yang dipengaruhi oleh tahun 2054 dan tindakan berani, pria tua ini mengguncang semua aspek kehidupan Raito yang selama ini ia tutupi—mulai dari impian dan pekerjaan, persahabatan, cinta, pernikahan, hingga keluarga. Di tengah hari-hari yang kacau setelah gagal melamar kekasihnya, Tsutsui Rin, Raito harus menghadapi benturan antara nilai-nilai dari \"masa depan\" tahun 2054 dan \"masa kini\" tahun 2024. Bisakah Raito menjalani hidupnya dengan baik?",
	densetsunohead: "Sebuah drama spin-off dari \"Densetsu no Head Shou\" telah lahir! Tatsujin, Seyama, dan Toujou memutuskan untuk berpartisipasi dalam sebuah \"Permainan Kematian.\" Tanpa disengaja, seorang siswi SMA yang serius, Kaede, terseret ke dalamnya! Karena Kaede, yang berperan sebagai wasit, memiliki \"perasaan yang sedikit berbeda,\" arah permainan kematian ini menjadi penuh gejolak.",
	ryosangatarikos3: "Komukai Riko, anak kedua dalam keluarganya, kembali ke rumah setelah kematian kakeknya dan menemukan model plastik setengah jadi. Dipandu ke toko langganan sang kakek, Riko memutuskan menyelesaikan model tersebut dan menghabiskan musim panas di rumah, demi memahami kakeknya dan keluarganya lebih dalam.",
	nogicinema: "Sepuluh member populer dari Nogizaka46, termasuk Shiraishi Mai dan Saito Asuka, membintangi masing-masing satu episode dalam drama ini. Sutradara dari drama ini adalah seorang sutradara video musik yang telah bekerja dengan sejumlah artis terkenal, seorang sutradara iklan yang telah memenangkan Grand Prix di Cannes, dan seorang sutradara film muda yang telah meraih penghargaan di festival film di seluruh dunia.",
	shiosuketoamami: "Kubo Shiori  membintangi serial original Paravi \"Shiosuke to Amami -Soba ga Dekiru Made Tante-\", sebuah spin-off dari drama TBS \"Ishiko to Haneo: Sonna Koto de Uttaemasu?\" dengan memerankan karakter bernama Amatsuyu Kayami, dan yang menjadi lawan lainnya adalah Shiozaki Keisuke (Oda Oideyasu)",
	shotenintantei: "Sebuah lanjutan dari karya sebelumnya \"Hikkoshi Tantei Sakura\". Kisah ini menampilkan Tendo Sakura yang bekerja di toko buku dan terlibat dalam sebuah insiden di tur misteri penulis idolanya, di mana ia kembali terjun untuk memecahkan misteri tersebut.",
	deathgame: "Seorang penulis skenario yang dikucilkan dari industri TV beralih menjadi 'penulis game maut' dalam drama balas dendam, menggunakan kreativitas dan sifat kejamnya untuk membalas dendam dengan mengatur permainan maut yang mematikan.",
	miren: "Kosaka Kento, seorang editor majalah manga Comic Boon, diam-diam menjalin hubungan dengan Fukada Yuzu, seorang mangaka idola populer. Di tempat kerja, mereka berpura-pura hanya memiliki hubungan profesional sebagai editor dan penulis. Namun, hubungan mereka terguncang ketika Suzuki Minami, rekan lamanya, muncul sebagai karyawan baru.",
	madder: "Nakano Akane, siswi jenius dengan nilai ujian masuk sempurna pertama dalam sejarah Seiran Gakuen, merasa hidup membosankan karena terlalu pintar. Namun, setelah bertemu Kurokawa Yu, pemuda yang dicurigai sebagai pelaku pembunuhan, ia tertarik pada dunia kejahatan dan mulai membuat kekacauan kecil di sekolah. Hingga akhirnya, pembunuhan sungguhan terjadi dan memicu rangkaian kasus mengejutkan yang mengguncang seluruh Jepang.",
	nogifettucine: "Nogizaka46 x Fettucine Gummi merupakan short drama kolaborasi antara Nogizaka46 dengan produk manisan Fettucine Gummi. Di short drama ini memperkenalkan juga coupling di single ke-25 \"Sayonara, stay with me\"",
	// ------------
	// // ------------
	// // ------------
	yononakani: "Saki, seorang gadis SMA yang sudah lama bolos bersekolah, bekerja paruh waktu sebagai penasihat \"akhir hayat\". Bersama dengan Keizo, seorang kakek-kakek yang bekerja dengannya, mereka membantu orang-orang dari semua lapisan masyarakat dengan rencana 'akhir hayat' mereka. Pekerjaan Saki penuh dengan bahaya, dan dia menghabiskan hari-harinya membantu orang-orang yang mencoba meninggalkan wasiat untuk keluarga mereka jika terjadi keadaan darurat, atau yang hanya memiliki beberapa hari tersisa untuk hidup dan ingin melestarikan kenangan mereka, dan membantu mereka dengan kegiatan 'akhir hayat' mereka.",
	sayounarakonbanwa: "Film menyentuh hati disutradarai oleh Yoichiro Fukada ini berkisah tentang Hanzawa Yohei (diperankan Hagiwara Riku), seorang pegawai kantoran yang memiliki kehidupan super aneh. Tiba-tiba ia jatuh cinta dengan kekasihnya yang berpikir untuk menikah, dan hantu wanita, Aisuke (diperankan oleh Kubo Shiori). Aisuke yang polos dan murni yang tidak mengalami romansa saat dia masih hidup, dan Yohei yang canggung dalam cinta yang tidak memperhatikan perasaan pihak lain. Pada awalnya, hubungan itu canggung, namun seiring waktu berjalan menghabiskan waktu di ruang yang sama, mereka saling memahami dan memperdekat jarak",
	shiawasenakereba: "Ex-member Nogizaka46, Kitagawa Yuri, merilis karya pertamanya sebagai penulis naskah dan pemeran utama! Kitagawa Yuri, yang lulus dari Nogizaka46 pada Juni 2023 sebagai member dari gen-4, telah menyelesaikan karya orisinal yang telah ia rencanakan dan tulis sejak masih aktif, dimana Kitagawa sendiri menjadi pemeran utamanya juga. Selain Kitagawa, sebagai pemeran utama lainnya, tampil 11 member gen-4 lain yang merupakan teman seangkatannya di Nogizaka46, termasuk Endo Sakura dan Kaki Haruka yang saat ini aktif sebagai ace grup. Karya ini merupakan yang pertama dalam sejarah Nogizaka46, di mana mantan member menulis naskah asli dan skripnya, sementara member yang aktif berperan dalam film tersebut.",
	// // ------------
	// // ------------
	// // ------------
	nanaminkoisuruFuyu: "Hashimoto Nanami, lahir di Asahikawa, Hokkaido, member dari grup idola populer Nogizaka46, melakukan perjalanan sendirian dengan sebuah buku tentang Hokkaido. Inilah hiburan intelektual yang menyampaikan pesona membaca, sambil melihat pesona Nanami sendiri. Konten khusus ini diperuntukan bagi yang rindu akan sosok Nanamin, dan tertarik dengan dunia sastra Jepang.",
	nanaminkoisuruNatsu: "Hashimoto Nanami, lahir di Asahikawa, Hokkaido, member dari grup idola populer Nogizaka46, melakukan perjalanan sendirian dengan sebuah buku tentang Hokkaido. Inilah hiburan intelektual yang menyampaikan pesona membaca, sambil melihat pesona Nanami sendiri. Konten khusus ini diperuntukan bagi yang rindu akan sosok Nanamin, dan tertarik dengan dunia sastra Jepang.",
	nogizakabooks: "Dalam BluRay Nogizaka46 Hashimoto Nanami no Koisuru Bungaku terdapat bonus, salah satunya Nogizaka Books. Di video singkat ini, member terpilih akan menyampaikan buku novel favoritnya baru-baru ini.",
	nogizakaescape: "Member Nogizaka46 meninggalkan kehidupan sehari-hari yang sibuk untuk sejenak melarikan diri. Dua member yang dipilih berdasarkan kombinasi tertentu akan memilih \"tempat yang sangat ingin mereka kunjungi sekarang\" dan merencanakan perjalanan 1 malam 2 hari mereka sendiri. Melalui perjalanan yang hanya dilakukan oleh dua orang, acara variety berbentuk dokumenter ini mengamati sisi asli para member dan hubungan mereka berdua!",
	// // ------------
	// // ------------
	// // ------------
	matsumuraShihsouhin: "Matsumura Sayuri dari Nogizaka46 melakukan sebuah project untuk menentukan citarasa baru Sapporo Ichiban Waraa.",
	asusanpo: "Seri Sapporo Ichiban ke-3 ini berjudul Asusanpo. Member gen-4 (Endo Sakura, Kakehashi Sayaka, Kanagawa Saya) diberikan sebuah kegiatan untuk memperkenalkan senpainya, Saito Asuka-san pada pesona lokal Jepang, karena mereka mendengar kalau Asuka-san selalu di luar negeri dan tampaknya sudah mengarahkan pandangannya dari Jepang sepenuhnya. Untuk menyampaikan pesona yang tidak ditemukan di luar negeri, mereka mencoba mengajak Asuka.",
	cupstarnogimart: "Nogimart no Hibi adalah film pendek komedi yang dirilis pada Mei 2020. Menceritakan member Nogizaka46 yang bekerja di toko kelontong bernama Nogi Mart, dengan komedian Satoshi Iizuka dari Tokyo 03 berperan sebagai manajer toko, dan memiliki anak yaitu diperankan oleh Saito Asuka.",
	cupstarsashimen: "Setelah sekian lama, dari Sapporo Ichiban Cupstar, dimulailah proyek baru bernama \"Sashimen\". Dalam proyek ini, para member Nogizaka46 akan muncul setiap bulannya dengan berpasangan, dan mereka akan menikmati percakapan sambil menikmati rasa Cupstar yang tidak biasa bagi mereka.",
	// // ------------
	// // ------------
	// // ------------
	collabyakubochannel: "Yakubo Channel (mengambil alih Kubo Channel), merupakan segmen food report dimana Yakubo Mio dari gen-4 akan melaporkan apa yang dimakan oleh para member Nogizaka46 saat Manatsu no Zenkoku Tour 2022.",
	collabasahiotonasenbatsu: "",
	selffmadeCompilation: "Kompilasi video yang dibuat oleh MoeFang.",
	fansubPartner: "",
	randomcontent: "Berbagai garapan MoeFang yang tidak terkategorikan, biasa kami sebut sebagai 'projek santai' atau 'selingan' dari garapan utama.",
	// // ------------
	// // ------------
	// // ------------
	livePerformance: "Disini adalah kumpulan berbagai garapan MoeFang Subs kategori konser atau perform grup Sakamichi maupun BokuAo.",
	nogi12bdltalk: "Sebuah event di mana bisa menikmati 4 hari penampilan 12th Year Birthday Live dalam satu hari. Selain itu, di antara setiap pertunjukan, juga menayangkan sesi talk show spesial yang direkam setelah konser. Selain member saat ini, para lulusan seperti Akimoto Manatsu, Shiraishi Mai, Takayama Kazumi, dan Higuchi Hina juga akan hadir sebagai tamu.",
	nogiskitsBDvol1: "Konten-konten Nogizaka Skits versi Blu-Ray edisi ke-1.",
	nogiskitsBDvol2: "Konten-konten Nogizaka Skits versi Blu-Ray edisi ke-2.",
	nogiskitsclub: "Ini adalah video khusus (lebih tepatnya video ucapan) yang sudah mendaftar club dalam situs resmi Nogizaka Skits.",
	nogiskiMachisowakan1: "Disini kita bisa melihat ekspresi para member gen-4 saat melihat berbagai skits, beserta pendapat para member yang tidak ditampilkan di televisi, tersedia hanya di HULU.",
	nogiskiMachisowakan2: "Disini kita bisa melihat ekspresi para member gen-3 dan gen-4 saat melihat berbagai skits, beserta pendapat para member yang tidak ditampilkan di televisi, tersedia hanya di HULU.",
	nogistartanjouwarukunai: "Disini kita bisa melihat unreleased scene dari Nogizaka Star Tanjou yang tidak ditayangkan di televisi, tersedia hanya di HULU.",
	shinnogistarchousen: "Ini adalah cuplikan di balik layar Shin-Nogizaka Star Tanjou yang tidak ditayangkan di televisi, tersedia hanya di platform HULU. Kita bisa melihat berbagai persiapan, kegugupan, kesiapan anak-anak gen-5 dalam penampilan bernyanyi.",
	shinnogistarHajimeteTalk: "Menyanyi dan menari adalah hal baru, inilah Nogizaka46 gen-5 yang baru debut! Gen-5 ini ditantang untuk berbincang satu sama lain untuk pertama kalinya. Mereka akan melempar dadu dan memilih topik pembicaraan secara improvisasi.",
	// // ------------
	// // ------------
	// // ------------
	// schooloflock: "",
	gen5msg: "Ini merupakan lembar profil para member baru gen-5, beserta perkenalan diri mereka pertama kali dengan para penggemar.",
	// // ------------
	// // ------------
	// // ------------
	// skebingo: "",
	bokuaorandom: "Berbagai video random mengenai grup Boku ga Mitakatta Aozora",
	bokuaoDocu: "Berbagai video dokumenter dari Boku ga Mitakatta Aozora",
	SakamichiAozora: "\"Sakamichi no Mukou ni wa Aozora ga Hirogatteita\" merupakan acara pelatihan idola tipe Sparta yang bertujuan mengejar super idol Nogizaka46. Para siswanya adalah yang baru saja debut pada bulan Agustus tahun ini dengan pengalaman dunia hiburan hanya 2 bulan, Boku ga Mitakatta Aozora. Mereka yang belum mengenal satu sama lain di antara 23 orang ini didampingi wali kelas dan wakil wali kelas yang tiba-tiba ditugaskan ke kelas ini, duo komedian Jepang Chocolate Planet, Osada Shohei dan Matsuo Shun.",
};