
// =======================
// DESKRIPSI B
// =======================

const descEpisodeSynopsis = {
"01" : "Another Sky adalah acara mingguan yang menampilkan orang-orang terkenal mengunjungi luar negeri, gabungan antara cuplikan lokasi dan segmen studio. Dalam episode ini, Saito Asuka mengunjungi London.",
"02" : "Di sini, Ayane bersama Watanabe Miria dan Kitano Hinako dan atas izin spesial dari All Nippon Airways (ANA), akan mengelilingi daerah bandara dan mencari pengetahuan tentang pesawat terbang! Kira-kira keseruan seperti apa?",
"03" : "Konten nostalgia ini adalah SHOWROOM terakhirnya Hashimoto Nanami. Disini dia mengadakan acara menjelang perilisan photobook \"2017\" dan perilisan perdana MV Naimononedari, single solonya. Kalau kalian kangen pengen nonton lagi, silakan. Videonya memangkurang jernih (640x360) jadi mohon maaf ya.",
"04" : "Mouse original web videos \"Natsu Omoide no Tsukurikata feat. 3rd Gen Nogizaka46\" dan \"Tantangan mengedit untuk Nogizaka46 gen-3\" yang menampilkan Ozono Momoko, Yamashita Mizuki, dan Yoda Yuuki dirilis di situs resmi Mouse pada 27 Agustus 2018.",
"05" : "Video cut kurang dari satu menit, dimana Hashimoto Nanami mengunjungi Sapporo Daiichi High School sebagai Kepala Polisi Satu Hari.",
"06" : "Video cut 2 menit dari making of film \"Shinigami: The Death Handler\", dimana Suzuki Ayane berperan dalam film tersebut dengan nama Ofuji.",
"07" : "Sebuah episode dari The Gift dengan durasi hanya 2 menit ini, dimana Morita Hikaru (Sakurazaka46) akan memberikan sebuah hadiah Natal kepada TAKAHIRO-sensei",
"08" : "Video cut 2 menit dari making of film \"Shinigami: The Death Handler\", dimana Suzuki Ayane berperan dalam film tersebut dengan nama Ofuji.",
"09" : "Kakehashi Sayaka berpartisipasi untuk pertama kalinya dalam sebuah iklan Suenaga Group. Kali ini dia akan di-interview bagaimana kesannya selama proses shooting iklan pertama kalinya.",
"10" : "Kakehashi Sayaka kembali berpartisipasi untuk kedua kalinya dalam sebuah iklan Suenaga Group. Kali ini dia akan di-interview bagaimana kesannya selama proses shooting. Disini juga dia membuat sebuah lagu dengan tema yang sudah dipilih.",
"11" : "Dalam rilisan santai durasi 3 menit ini, dalam acara Sakagami Animal Kingdom, mereka mengunjungi Yoda Yuuki. Kalian sudah tau kalau Yoda ini punya peliharaan di kampung halamannya. Disini, dia sedikit ngobrol-ngobrol tentang peliharannya baik di kampung halamannya atau di rumahnya di Tokyo.",
"12" : "Dalam rilisan santai durasi 7 menit ini, dalam acara Hirumaehotto NHK, mereka berkesempatan untuk mewawancarai Shibata Yuna, member Nogizaka gen-4 yang mencintai Chiba Lotte Marines sejak kecil. Disini dia menceritakan sedikit kesannya terhadap tim baseball kesayangannya itu, dan dampak darinya yang membuatnya bisa menjadi seorang idol seperti sekarang.",
"13" : "Di kesempatan kali ini saya mencoba sub 3 menit dari Real Sound. Real Sound melakukan wawancara dengan Higuchi Hina dan Suzuki Ayane, dengan fokus pada album baru Nogizaka46 \"Time flies\". Namun dalam video ini adalah menyampaikan kesan pertama baik Hinachima pada Ayane maupun sebaliknya.",
"14" : "Di kesempatan kali ini kami mencoba video cut salah satu episode dari The Toppa File, dimana Umezawa Minami dan Shibata Yuna berperan dalam drama pendek disini. Seperti biasa dalam acara ini, penonton juga tamu yang hadir diberikan pertanyaan yang berhubungan dengan drama yang ditampilkan. Kali ini drama yang dimainkan Ume dan Yuna adalah misteri tubuh manusia.",
"15" : "Seperti biasa MoeFang merilis garapan santai, kali ini videonya cuman 2 menit. Di sini ada Manatsu, Kiichan, Yoda dan Kakki. Mereka diwawancarai siapa member yang paling banyak berubah dalam 10 tahun terakhir sejak pembentukan grup tahun 2011 yang lalu. Kalau yang mau download sebagai koleksi, silakan~",
"16" : "Di kesempatan kali, MoeFang mencoba ngesub konten kegiatan H-1 sebelum konser 9th Birthday Live 2nd Gen atau konser kelulusannya Hori Miona yang disiarkan di ABEMA beberapa waktu yang lalu. Sebuah acara berdurasi 53 menit yang mana hanya diisi oleh 8 orang gen-2 ini akan menjawab/memainkan 1 pertanyaan dari 3/4 pilihan para penonton. Yang pastinya ada keseruan tersendiri di acara ini. ",
"17" : "Di garapan selingan ini saya mau ngesub salah satu episode di LIFE! di Mei 2019 lalu, yang mana Ikuta Erika mencoba bermain conte alias sketsa komedi. Dan setelah itu, ada sesi bincang-bincang yaitu Ikuchan akan dites seberapa buruk kah dia dalam berbohong alias mudah ketahuan kalo berbohong.",
"18" : "\"Sonotoki, Cupstar\" merupakan CM berdurasi 15 detik yang menampilkan beberapa member Nogizaka46 dengan berbagai latar cerita. Kini di April 2022 sudah mencapai episode 21 (atau Season 2 episode 11). Yang saya sediakan langsung berupa folder Google Drive.",
"19" : "HEY! HEY! NEO! MUSIC CHAMP' adalah acara musik sesekali yang sudah berjalan lama dengan pertunjukan dan wawancara yang dipandu oleh duo komedi Downtown. sebelum itu (ketika masih reguler). Pada tanggal 10 April 2021, mereka mengundang Sakurazaka46. Sambil menujukkan karya hasil gambarannya Tenchan, mereka juga menampilkan juga single ke-2 “BAN”.",
"20" : "\"Eiga Ongaku wa Subarasashii!\" merupakan program yang menampilkan musik film terbaik dunia yang dibawakan langsung oleh orkestra dan dinyanyikan oleh berbagai penyanyi cantik. Kali ini, ex-member Nogizaka46 Ikuta Erika membawakan lagu film populer, yaitu The Devil Wears Prada dan \"Xanadu\".",
"21" : "Kakehashi Sayaka kembali berpartisipasi untuk ketiga kalinya kalinya dalam sebuah iklan Suenaga Group (pertama pada tahun 2020, dan kedua tahun 2021). Kali ini dia akan di-interview bagaimana kesannya selama proses shooting di dalam trem di kampung halamannya, Okayama. Disini juga dia membawakan lagu dari iklan sebelumnya dengan aransemen yang baru.",
"22" : "Episode kedua menampilkan Endo Sakura, yang merupakan brand ambassador JCB \"Disney★\". Dari konten yang disiarkan di Disney+, ia telah memilih kenangan yang paling diingatnya bersama Disney.",
"23" : "Nogizaka46 Kubo Shiori adalah model eksklusif untuk majalah mode wanita \"seventeen\". Dalam edisi kali ini bertemakan apa yang ingin dilakukan Kubo Shiori di musim panas, mengenakan pakaian yang ingin ia pakai, dan pergi ke tempat-tempat yang ingin ia kunjungi!",
"24" : "Yoda Yuuki untuk pertama kalinya memainkan peran utama dalam serial drama \"Ryosangata Riko: Puramo Joshi no Jinsei Kumitate Ki\" (TV Tokyo dan juga tersedia di dTV), yang dimulai pada 30 Juni. Dalam wawancara ini, ia berbicara terus terang tentang perasaannya saat mendapatkan peran utama pertamanya, tentang proses syutingnya, dan tentang kesulitan menyeimbangkan pekerjaan idola dan akting.",
"25" : "Dalam selingan kali ini kami ngesub konten salah satu member Sakurazaka46 yaitu Tamura Hono dalam program seputar binatang, Ura Torechaimashita. Dia berkunjung ke sebuah kafe anjing mameshiba. Ditambah keimutan anjing-anjing ini akan menambah kita yang menonton terasa 'iyasaremashita' alias tersembuhkan :)",
"26" : "Real Sound melakukan wawancara dengan Tsutsui Ayame dan Kakehashi Sayaka, dengan fokus pada single baru Nogizaka46 yang ke-30 \"Suki to Iu no wa Rock da ze\". Video ini menyampaikan hal yang mereka sukai baik Ayamen ke Saachan maupun sebaliknya.",
"27" : "Real Sound melakukan wawancara dengan Shibata Yuna dan Tamura Mayu dengan fokus pada single baru Nogizaka46 yang ke-30 \"Suki to Iu no wa Rock da ze\". Video ini menyampaikan hal yang mereka sukai baik Mayutan ke Yuna maupun sebaliknya. Tak lupa juga mereka akan menjawab pertanyaan dari member sebelumnya, Ayamen dan Saachan.",
"28" : "Seorang pekerja kantoran, Kanoumi Murano (Ikuta Erika), tiba-tiba menderita penyakit aneh yang disebut \"sindrom melodi otak,\" yang menyebabkan otaknya bereaksi tidak normal jika dia tidak bertindak sesuai dengan musik yang diputar di otaknya, yang dalam kasus terburuk menyebabkan kematian. Tanpa obat untuk penyakit yang tidak diketahui ini, yang hanya memiliki beberapa kasus, Kanoumi berada dalam belas kasihan melodi dari berbagai genre yang diputar di otaknya ke mana pun dia pergi, apakah dia sedang rapat atau dalam perjalanan pulang. Suatu hari, Kanoumi, yang takut tidak tahu kapan melodi akan bermain di otaknya, bertemu dengan Mitsuru Shindo (Inaba Yu), yang dikabarkan sebagai orang aneh di perusahaannya.",
"29" : "Di kesempatan kali ini, gen-5 Inoue Nagi dan Sugawara Satsuki mendapat interview singkat dalam channel YouTube-nya Sapporo Ichiban mengenai CM yang telah mereka perankan, dan pengalamannya saat syuting NogiMart bersama member senpai dan Tokyo03.",
"30" : "Dalam acara ini, kapten Akimoto Manatsu dan Iwamoto Renka gen-3 akan mencoba sarapan spesial yang sedikit mewah di sekitaran daerah Ginza. Berbagai menu makanan yang tidak biasa dihidangkan di rumah-rumah, mereka akan menikmatinya! Seperti apakah keseruannya?",
"31" : "Dalam acara ini, kapten Akimoto Manatsu dan Iwamoto Renka gen-3 akan mencoba makan siang spesial yang sedikit mewah. Berbagai menu makanan mewah dengan cita rasa yang unik dibandingkan di tempat lain ini, mereka akan menikmatinya! Seperti apakah keseruannya?",
"32" : "Di kesempatan kali ini saya kembali mencoba sub pendek dari Real Sound. Real Sound kali ini melakukan wawancara dengan Shibata Yuna dan Hayashi Runa dengan fokus pada single baru Nogizaka46 yang ke-31 \"Koko ni wa nai mono\". Video ini menyampaikan hal yang mereka tidak miliki (nai mono) baik Runa ke Yuna maupun sebaliknya.",
"33" : "Dalam rilisan ini kita melihat Suzuki Ayane yang tampil di acara televisi Prefektur Akita. Ia jalan-jalan mengunjungi 2 toko yang pernah ia kunjungi ketika masih kecil, sambil menjawab beberapa pertanyaan.",
"34" : "Dalam acara ini, Kaki Haruka dan Kanagawa Saya dari gen-4 ini diundang untuk menikmati cara bersenang-senang di area bermain Disneyland yang saat itu tengah merayakan ulang tahunnya yang ke-40. Dalam bagian pertama ini, mereka akan menikmati parade siang hari dimana banyak karakter-karakter Disney tampil.",
"35" : "Dalam acara ini, Kaki Haruka dan Kanagawa Saya dari gen-4 ini diundang untuk menikmati cara bersenang-senang di area bermain Disneyland yang saat itu tengah merayakan ulang tahunnya yang ke-40. Dalam bagian kedua ini, mereka akan menikmati hidangan limited edition yang hanya tersedia saat ulang tahunya Disneyland Japan.",
"36" : "Dalam acara ini, Kaki Haruka dan Kanagawa Saya dari gen-4 ini diundang untuk menikmati cara bersenang-senang di area bermain Disneyland yang saat itu tengah merayakan ulang tahunnya yang ke-40. Dalam bagian ketiga ini, mereka akan menikmati kembali hidangan limited edition yang hanya tersedia saat ulang tahunya Disneyland Japan juga monorail yang sangat beruntung jika bisa menaikinya.",
"37" : "Dalam acara BananaSand ini, Kubo Shiori dan Kaki Haruka pertama kalinya mampir kemari dan menantang tantangan yaitu menyanyikan lagu yang mereka inginkan namun untuk terus mempertahankan nadanya sambil mendengarkan nada yang sudah dimodifikasi. Apakah mereka berdua akan berhasil?",
"38" : "Dalam acara \"Doyou wa Nani Suru\" ini, ex-member Nogizaka46, Saito Asuka akan pergi ke Atami di Prefektur Shizuoka untuk liburan santai bersama salah satu orang yang ia sukai, yaitu Chosuriki-sanm sang mantan pegulat yang kini sangat populer di kalangan generasi muda TikTok. Memiliki perbedaan usia dan pengalaman, inilah pertemuan pertama dari kombinasi unik!",
"39" : "Di Jepang masa depan yang dekat, teknologi penggunaan Life Log dan pengembangan Life Cast telah berkembang. Life Log adalah data tentang kehidupan sehari-hari, minat, dan gaya bicara seseorang selama hidupnya. Dengan menyuntikkan data ini ke dalam robot dengan baik, teknologi ini dapat menciptakan sosok yang sangat mirip dengan orang tersebut, seperti klon (Life Cast). Koshizu Inori (Nishino Nanase) menjadi terkenal sebagai Life Caster yang mampu membuat Life Cast berkualitas tinggi. Namun, Inori tidak menyukai hasil karyanya, menyebutnya sebagai \"boneka tanpa jiwa\", dan merencanakan untuk berhenti dari pekerjaannya. Suatu hari, Inori menerima permintaan pembuatan Life Cast dari virtual idol yang pernah sangat terkenal, Tasogare Kiera. Inori kesulitan mengumpulkan data Life Log dari idol virtual yang populer lebih dari 50 tahun yang lalu ini, tetapi seiring berjalannya waktu, ia mulai menyentuh rahasia tersembunyi dari masa lalu Kiera.",
"40" : "Ini adalah penampilan pertama dari single Nogizaka46 berjudul \"Monopoly\". Center-nya untuk kali ini adalah dari gen-4, Kaki Haruka dan Endo Sakura. Bagi yang ingin menyaksikannya, silakan.",
"41" : "LALALife merupakan sebuah variety show dengan pembawa acara Masakazu Mimura dan Takataka Aoki, disiarkan dari stasiun TBS Setiap Jumat mulai pukul 11:30. Di kesempatan kali ini, Yoda Yuuki berkesempatan pergi ke Taiwan dan makan gyoza disana seharian. Meskipun awalnya ragu karena kesulitan dalam segi bahasa, namun ia dengan cepat terbiasa. Seperti apa keseruannya?",
"42" : "Nogizaka46 Berpartisipasi untuk pertama kalinya! Mereka terkesima dengan pengalaman yang unik di pedalaman Chiba! Ioki Mao dan Sugawara Satsuki mengunjungi penginapan yang penuh dengan pemandangan musiman yang indah di Prefektur Chiba. Mereka menemukan telepon hitam di rumah tua dengan atap jerami. Mereka menikmati berbagai \"pengalaman pertama\" yang unik dari penginapan ini, mulai dari rendaman kaki hingga nasi di tungku, hingga mi udon buatan tangan, sambil menjelajahi pesonanya!",
"43" : "Impian Himura-san menjadi kenyataan! Narator Shiraishi Mai juga terkesan! Mereka mengantarkan member Nogizaka46 yang sudah masuk usia 20 tahun ke upacara kedewasaan di tahun 2024.",
"44" : "Himutaro berjalan-jalan di sekitar Kanda hingga Jinbocho dengan Endo Sakura dari Nogizaka46 kali ini. Mereka memulai dari Kuil Kanda. Mampir ke Yushima Seido, dan jika beruntung, mereka akan melintasi Hijiribashi, di mana mereka bisa melihat berbagai kereta api. Mereka juga berpose bersama di area yang ditanami sakura. Ketika melewati Stasiun Kudanshita, mereka melihat Nippon Budokan di kejauhan. Bagi Himutaro, berjalan-jalan bersama di sini penuh dengan kenangan yang mendalam. Terakhir, mereka menikmati hadiah berupa kari yang lezat dengan banyak rempah!",
"45" : "\"Waraidane\" adalah sebuah program talk show dengan pembawa acara Uchimura Teruyoshi dan duo komedian Summers. Konten percakapan hanya akan mencakup \"pertama kali dibahas\" yang belum pernah dibicarakan di TV sebelumnya! Di tamu ketiga kali ini, Nogizaka46 bersama Ijiri Okada akan tampil!",
"46" : "Dengan Yumiki Nao dan Ioki Mao, bisakah dua member Nogizaka46 ini mencapai tempat baru tanpa smartphone? Mereka akan melakukan semacam perjalanan waktu ke era Showa dan Heisei, ketika belum ada smartphone! Penyelidikan mendalam tentang apa yang dilakukan generasi Showa ketika belum ada smartphone, termasuk 'hubungan jarak jauh' dan 'membeli tiket'. Saksikan perjalanan unik mereka dengan kesimpulan mengejutkan yang tidak terduga...",
"47" : "Tamu pada 2 November adalah Saito Asuka, aktor dan model yang sebelumnya aktif sebagai member Nogizaka46 dan lulus dari grup pada konser Mei tahun lalu. Berkunjung ke Osaka, ia mengenang masa lalunya, dari debut pada usia 13 hingga pengalaman yang penuh warna sebagai idola. Saat itu, ia sangat termotivasi oleh kerja keras para member dan tak punya keinginan lain selain menjadi bagian dari Nogizaka46, sehingga sempat mempertimbangkan pensiun saat lulus. Namun, dorongan ibunya membuatnya melanjutkan karier di dunia hiburan. Baginya, Osaka adalah tempat yang memungkinkan dirinya tampil apa adanya, bertemu orang-orang yang tulus dengan canda yang penuh kasih. Ia merasa penting untuk hidup dengan cinta dalam setiap interaksi, dan Osaka menginspirasinya menjadi pribadi yang lebih penuh kasih.",
"48" : "Ini adalah penampilan pertama dari single terbaru Nogizaka46 yang ke-37 berjudul \"Hodoukyou\". Center-nya untuk kali ini adalah dari gen-4, Endo Sakura, yang juga formasi senbatsunya diumumkan di waktu yang sama. Bagi yang ingin menyaksikannya, silakan.",
"49" : "Sebuah video singkat dari Nogi Douga yang akan memperlihatkan dibalik layar pembuatan MV \"Hodoukyou\" sekaligus saat penayangan pertama di Nogizaka Haishinchuu.",
};
console.log(descEpisodeSynopsis);

// =======================
// NAMA ACARA
// =======================

const nameShow = {
"01" : "アナザースカイ「乃木坂４６・齋藤飛鳥がロンドンで鮨店を再訪。涙の理由とは」",
"02" : "乃木坂46 鈴木絢音の「そら気分～ヒコーキに会いたい!!」",
"03" : "SHOWROOM",
"04" : "#最高の夏の思い出の作り方 feat. 乃木坂46 3期生",
"05" : "今日ドキッ！  一日警察署長 橋本奈々未",
"06" : "死神遣いの事件帖",
"07" : "The Gift 〜大切なあなたへ〜",
"08" : "Cinema Addict",
"09" : "Modelpress",
"10" : "Modelpress",
"11" : "坂上どうぶつ王国",
"12" : "NHK ひるまえほっと",
"13" : "Real Sound 「大人っぽさと髪の毛にびっくり！？」",
"14" : "THE 突破ファイル",
"15" : "まるっと！サタデー",
"16" : "乃木坂46堀未央奈卒業＆2期生ライブ前日記念！「緊急生特番！2期生8人だけ！",
"17" : "LIFE！～人生に捧げるコント～』",
"18" : "そのとき、カップスター",
"19" : "HEY! HEY! NEO! MUSIC CHAMP",
"20" : "映画番組はすばらしい!",
"21" : "Modelpress",
"22" : "Disney",
"23" : "Seventeen",
"24" : "与田祐希、乃木坂46加入前は〇〇女子だった！？地上波連ドラ初主演で想いを告白",
"25" : "ウラ撮れちゃいました",
"26" : "Real Sound 「甘えん坊なところにキュン！」",
"27" : "Real Sound 「頭を撫でればよかった！」",
"28" : "世にも奇妙な物語'22夏の特別編 「メロディに乗せて」",
"29" : "井上和・菅原咲月にインタビュー！",
"30" : "プチブランチ",
"31" : "プチブランチ",
"32" : "Real Sound 「思ってもない回答に驚き！」",
"33" : "秋田で絢音ちゃんに聞きたい！Youtube特別版",
"34" : "プチブランチ",
"35" : "プチブランチ",
"36" : "プチブランチ",
"37" : "バナナサンド",
"38" : "土曜はナニする！？",
"39" : "世にも奇妙な物語 23年秋の特別編「走馬灯のセトリは考えておいて」",
"40" : "乃木坂配信中",
"41" : "ララLife",
"42" : "全国ボロいい宿",
"43" : "ひむバス！バナナマン日村さんの夢！乃木坂46メンバーをサプライズ送迎！ ",
"44" : "バナナマン日村が歩く！ウォーキングのひむ太郎",
"45" : "内村&さまぁ~ずの初出しトークバラエティ 笑いダネ",
"46" : "スマホがない時、どうしていたの",
"47" : "アナザースカイ 齋藤飛鳥",
"48" : "乃木坂配信中",
"49" : "のぎ動画 歩道橋 メイキング付きSpecial Edition",
};
console.log(nameShow);

// =======================
// EPISODE
// =======================

const descEpisode = {
"01" : "| 190308 Another Sky",
"02" : "| 191124 Suzuki Ayane no Sora kibun",
"03" : "| 170217 SHOWROOM",
"04" : "| 180827 Natsu no Omoide",
"05" : "| 161013 KYO-DOKI",
"06" : "| Shinigami zukai no Jiken Jo",
"07" : "| 201214 The Gift",
"08" : "| 210809 Cinema Addict",
"09" : "| 200707 Suenaga Group CM + Interview",
"10" : "| 210825 Suenaga Group CM + Interview",
"11" : "| 210625 Sakagami Animal Kingdom",
"12" : "| 211031 NHK Hirumaehotto",
"13" : "| 211215 Real Sound",
"14" : "| 210916 The Toppa File",
"15" : "| 211211 Marutto! Saturday",
"16" : "| 210327 ABEMA Emergency Special Program! Only 8 2nd-gen member!",
"17" : "| 190506 Life! Jinsei ni Sasageru Conte",
"18" : "| Sapporo Ichiban",
"19" : "| 220410 HEY! HEY! NEO! Music Champ",
"20" : "| 220514 Eiga Ongaku wa Subarasashii!",
"21" : "| 220707 Suenaga Group CM + Interview",
"22" : "| 220715 Disney Plus α Story Vol.2",
"23" : "| 220726 Seventeen Kubo Shiori no Natsu ni shitai koto",
"24" : "| 220728 Yoda Yuuki, Nogizaka46 Kanyuu mae wa ○○ Joshi datta!",
"25" : "| 220721 Ura Torechaimashita",
"26" : "| 220902 Real Sound",
"27" : "| 220910 Real Sound",
"28" : "| 220618 Yo nimo Kimyou na Monogatari 2022 - Melody ni Nosete (Ikuta Erika)",
"29" : "| 221105 Nogizaka Maitsuki Gekijou",
"30" : "| 221123 Petit Brunch",
"31" : "| 221130 Petit Brunch",
"32" : "| 221213 Real Sound",
"33" : "| 230418 Akita de Ayane-chan ni Kikitai!",
"34" : "| 230508 Petit Brunch",
"35" : "| 230516 Petit Brunch",
"36" : "| 230523 Petit Brunch",
"37" : "| 230627 BananaSand",
"38" : "| 230902 Doyou wa Nani suru!?",
"39" : "| 231111 Yo nimo Kimyou na Monogatari 2023",
"40" : "| 231114 Nogizaka Haishinchuu - Nogizaka46 \"Monopoly\" First Performance",
"41" : "| 231117 LALALIFE!",
"42" : "| 240218 Zenkoku Boroii Yado (Ioki Mao, Sugawara Satsuki, Sasaki Kumi CUT)",
"43" : "| 240223 Himubus Eps.9 (Nogizaka46 CUT)",
"44" : "| 240416 Walking no Himutaro (Endo Sakura)",
"45" : "| 240103 Waraidane",
"46" : "| 240721 Sumaho ga Nai Toki Dou Shiteita no?",
"47" : "| 241102 Another Sky",
"48" : "| 241109 Nogizaka Haishinchuu - Nogizaka46 \"Hodoukyou\" Senbatsu Formation Announcement & First Performance",
"49" : "| 250102 Nogi Douga - \"Hodoukyou\" Making of"
};
console.log(descEpisode);


// =======================
// DESKRIPSI AIRING
// =======================

const descOnAirDate = {
"01" : "8 Maret 2019",
"02" : "24 November 2019",
"03" : "17 Februari 2017",
"04" : "27 Agustus 2018",
"05" : "13 Oktober 2016",
"06" : "2020",
"07" : "14 Desember 2020",
"08" : "9 Agustus 2021",
"09" : "7 Juli 2020",
"10" : "25 Agustus 2021",
"11" : "25 Juni 2021",
"12" : "31 Oktober 2021",
"13" : "15 Desember 2021",
"14" : "16 September 2021",
"15" : "11 Desember 2021",
"16" : "27 Maret 2021",
"17" : "6 Mei 2019",
"18" : "31 Maret 2020 s/d ...",
"19" : "10 April 2022",
"20" : "14 Mei 2022",
"21" : "7 Juli 2022",
"22" : "15 Juli 2022",
"23" : "26 Juli 2022",
"24" : "28 Juli 2022",
"25" : "21 Juli 2022",
"26" : "2 September 2022",
"27" : "10 September 2022",
"28" : "18 Juni 2022",
"29" : "5 November 2022",
"30" : "23 November 2022",
"31" : "30 November 2022",
"32" : "13 Desember 2022",
"33" : "18 April 2023",
"34" : "8 Mei 2023",
"35" : "16 Mei 2023",
"36" : "23 Mei 2023",
"37" : "27 Juni 2023",
"38" : "2 September 2023",
"39" : "11 November 2023",
"40" : "14 November 2023",
"41" : "17 November 2023",
"42" : "18 Februari 2024",
"43" : "23 Februari 2024",
"44" : "16 April 2024",
"45" : "3 Januari 2024",
"46" : "21 Juli 2024",
"47" : "2 November 2024",
"48" : "9 November 2024",
"49" : "2 Januari 2025",
  };
console.log(descOnAirDate);


// =======================
// PARTISIPASI ORANG & TAMU
// =======================

const memberParticipate = {
"01" : "齋藤飛鳥",
"02" : "鈴木絢音、北野日奈子、渡辺みり愛",
"03" : "橋本奈々未",
"04" : "大園桃子、山下美月、与田祐希",
"05" : "橋本奈々未",
"06" : "鈴木絢音",
"07" : "森田ひかる",
"08" : "西野七瀬",
"09" : "掛橋沙耶香",
"10" : "掛橋沙耶香",
"11" : "与田祐希",
"12" : "柴田柚菜",
"13" : "樋口日奈、鈴木絢音",
"14" : "梅澤美波、柴田柚菜",
"15" : "秋元真夏、北野日奈子、与田祐希、賀喜遥香",
"16" : "乃木坂46 2期生",
"17" : "生田絵梨花",
"18" : "乃木坂46",
"19" : "桜坂46",
"20" : "生田絵梨花",
"21" : "掛橋沙耶香",
"22" : "遠藤さくら",
"23" : "久保史緒里",
"24" : "与田祐希",
"25" : "田村保乃",
"26" : "筒井あやめ、掛橋沙耶香",
"27" : "乃木坂46",
"28" : "生田絵梨花",
"29" : "井上和、菅原咲月",
"30" : "秋元真夏、岩本蓮加",
"31" : "秋元真夏、岩本蓮加",
"32" : "柴田柚菜、林瑠奈",
"33" : "鈴木絢音",
"34" : "賀喜遥香、金川紗耶",
"35" : "賀喜遥香、金川紗耶",
"36" : "賀喜遥香、金川紗耶",
"37" : "久保史緒里、賀喜遥香",
"38" : "齋藤飛鳥",
"39" : "西野七瀬",
"40" : "乃木坂46",
"41" : "与田祐希",
"42" : "五百城茉央、菅原咲月、佐々木久美",
"43" : "岩本蓮加、清宮レイ、松尾美佑、林瑠奈、黒見明香、川﨑桜、一ノ瀬美空、岡本姫奈",
"44" : "遠藤さくら",
"45" : "梅澤美波、岩本連加、与田祐希、賀喜遥香、弓木奈於",
"46" : "弓木奈於、五百城茉央",
"47" : "齋藤飛鳥",
"48" : "乃木坂46",
"49" : "乃木坂46",
  };
console.log(memberParticipate);


// =======================
// IMAGE THUMBNAIL main
// =======================

const imageThumbBig = {
"01" : "https://ik.imagekit.io/mLsKqNSuB/post/random/190308-anothersky00.jpg",
"02" : "https://ik.imagekit.io/mLsKqNSuB/post/sorakibun/sorakibun00.jpg",
"03" : "https://ik.imagekit.io/mLsKqNSuB/post/random/nanaminshowroom.jpg",
"04" : "https://ik.imagekit.io/mLsKqNSuB/post/random/mouse0.jpg",
"05" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kyodoki-nanami00.jpg",
"06" : "https://ik.imagekit.io/mLsKqNSuB/post/random/shinigami-00.jpg",
"07" : "https://ik.imagekit.io/mLsKqNSuB/post/random/thegift-00.jpg",
"08" : "https://ik.imagekit.io/mLsKqNSuB/post/random/cinema-addict-nanase-00.jpg",
"09" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kakehashi-cm1-0.jpg",
"10" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kakehashi-cm2-0.jpg",
"11" : "https://ik.imagekit.io/mLsKqNSuB/post/random/210625-yoda-sakagami-a.jpg",
"12" : "https://ik.imagekit.io/mLsKqNSuB/post/random/211031-hirumae-shibata.jpg",
"13" : "https://ik.imagekit.io/mLsKqNSuB/post/random/211215-realsound.jpg",
"14" : "https://ik.imagekit.io/mLsKqNSuB/post/random/210916-toppafile.jpg",
"15" : "https://ik.imagekit.io/mLsKqNSuB/post/random/211211-marutto-saturday-nogizaka46.jpg",
"16" : "https://ik.imagekit.io/mLsKqNSuB/post/random/219327-2kisei8nindake.jpg",
"17" : "https://ik.imagekit.io/mLsKqNSuB/post/random/190506-life-ikutaerika.jpg",
"18" : "https://ik.imagekit.io/mLsKqNSuB/post/random/sonotoki-cupstar.jpg",
"19" : "https://ik.imagekit.io/mLsKqNSuB/post/random/210410-heyheyneo-skz.jpg",
"20" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220514-eigaongaku.jpg",
"21" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kakehashi-cm3-0.jpg",
"22" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220715-disneyendo.jfif",
"23" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220726-seventeen-kubo-shiori.jpg",
"24" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220728-yoda-yuuki-kanyuu.jpg",
"25" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220721-uratorechaimashita.jpg",
"26" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220902-realsound.jpg",
"27" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220910-realsound.jpg",
"28" : "https://ik.imagekit.io/mLsKqNSuB/post/random/yonimo2022melody.jpg",
"29" : "https://ik.imagekit.io/mLsKqNSuB/post/random/221105-cupstar-interview.jpg",
"30" : "https://ik.imagekit.io/mLsKqNSuB/post/random/221123-petitbrunch.jpg",
"31" : "https://ik.imagekit.io/mLsKqNSuB/post/random/221130-petitbrunch.jpg",
"32" : "https://ik.imagekit.io/mLsKqNSuB/post/random/221213-realsound.jpg",
"33" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230418-ayanekikitai.jpg",
"34" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230508-petitbrunch.jpg",
"35" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230516-petitbrunch.jpg",
"36" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230523-petitbrunch.jpg",
"37" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230627-bananasand.jpg",
"38" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230902-doyounanisuru.jpg",
"39" : "https://ik.imagekit.io/mLsKqNSuB/post/random/yonimo2023setorikangaete.jpg",
"40" : "https://ik.imagekit.io/mLsKqNSuB/post/random/231114-ngzhaishinchuu-34monopoly.jpg",
"41" : "https://ik.imagekit.io/mLsKqNSuB/post/random/231117-lalalife-yodayuuki.jpg",
"42" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240218-zenkokuboroiiyado.jpg",
"43" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240223-himubus-fix.jpg",
"44" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240416-himutaro-endosakura.jpg",
"45" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240103-waraidane.jpg",
"46" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240721-sumahoganai.jpg",
"47" : "https://ik.imagekit.io/mLsKqNSuB/post/random/241102-anothersky00.jpg",
"48" : "https://ik.imagekit.io/mLsKqNSuB/post/random/241109-ngzhaishinchuu-37hodoukyou.jpg",
"49" : "https://ik.imagekit.io/mLsKqNSuB/post/random/250102-hodoukyou-bts.jpg",
  };
console.log(imageThumbBig);


// =======================
// IMAGE THUMBNAIL A
// =======================

const imageThumbA = {
"01" : "https://ik.imagekit.io/mLsKqNSuB/post/random/190308-anothersky01.jpg",
"02" : "https://ik.imagekit.io/mLsKqNSuB/post/sorakibun/sorakibun01.jpg",
"03" : "https://ik.imagekit.io/mLsKqNSuB/post/random/nanaminsr1.jpg",
"04" : "https://ik.imagekit.io/mLsKqNSuB/post/random/mouse1.jpg",
"05" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kyodoki-nanami01.jpg",
"06" : "https://ik.imagekit.io/mLsKqNSuB/post/random/shinigami-01.jpg",
"07" : "https://ik.imagekit.io/mLsKqNSuB/post/random/thegift-01.jpg",
"08" : "https://ik.imagekit.io/mLsKqNSuB/post/random/cinema-addict-nanase-01.jpg",
"09" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kakehashi-cm1-1.png",
"10" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kakehashi-cm2-1.jpg",
"11" : "https://ik.imagekit.io/mLsKqNSuB/post/random/210625-yoda-sakagami-b.jpg",
"12" : "https://ik.imagekit.io/mLsKqNSuB/post/random/211031-hirumae-shibata-a.jpg",
"13" : "doc/blank.png",
"14" : "https://ik.imagekit.io/mLsKqNSuB/post/random/210916-toppafile-a.jpg",
"15" : "doc/blank.png",
"16" : "https://ik.imagekit.io/mLsKqNSuB/post/random/219327-2kisei8nindake-a.jpg",
"17" : "https://ik.imagekit.io/mLsKqNSuB/post/random/190506-life-ikutaerika-a.jpg",
"18" : "https://ik.imagekit.io/mLsKqNSuB/post/random/sonotoki-cupstar1.jpg",
"19" : "https://ik.imagekit.io/mLsKqNSuB/post/random/210410-heyheyneo-skz-a.jpg",
"20" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220514-eigaongaku-a.jpg",
"21" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kakehashi-cm3-1.jpg",
"22" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220715-disneyendoa.jpg",
"23" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220726-seventeen-kubo-shiori1.jpg",
"24" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220728-yoda-yuuki-kanyuu1.jpg",
"25" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220721-uratorechaimashita1.jpg",
"26" : "doc/blank.png",
"27" : "doc/blank.png",
"28" : "https://ik.imagekit.io/mLsKqNSuB/post/random/yonimo2022melody-a.jpg",
"29" : "doc/blank.png",
"30" : "https://ik.imagekit.io/mLsKqNSuB/post/random/221123-petitbrunch-a.jpg",
"31" : "https://ik.imagekit.io/mLsKqNSuB/post/random/221130-petitbrunch-a.jpg",
"32" : "doc/blank.png",
"33" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230418-ayanekikitai-a.jpg",
"34" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230508-petitbrunch-a.jpg",
"35" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230516-petitbrunch-a.jpg",
"36" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230523-petitbrunch-a.jpg",
"37" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230627-bananasand-a.jpg",
"38" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230902-doyounanisuru-a.jpg",
"39" : "https://ik.imagekit.io/mLsKqNSuB/post/random/yonimo2023setorikangaete-a.jpg",
"40" : "doc/blank.png",
"41" : "https://ik.imagekit.io/mLsKqNSuB/post/random/231117-lalalife-yodayuuki-a.jpg",
"42" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240218-zenkokuboroiiyado-a.jpg",
"43" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240223-himubus-a.jpg",
"44" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240416-himutaro-endosakura-a.jpg",
"45" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240103-waraidane-a.jpg",
"46" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240721-sumahoganai-a.jpg",
"47" : "https://ik.imagekit.io/mLsKqNSuB/post/random/241102-anothersky01.jpg",
"48" : "doc/blank.png",
"49" : "https://ik.imagekit.io/mLsKqNSuB/post/random/250102-hodoukyou-bts-a.jpg",
  };
console.log(imageThumbA);

// =======================
// IMAGE THUMBNAIL B
// =======================

const imageThumbB = {
"01" : "https://ik.imagekit.io/mLsKqNSuB/post/random/190308-anothersky02.jpg",
"02" : "https://ik.imagekit.io/mLsKqNSuB/post/sorakibun/sorakibun02.jpg",
"03" : "https://ik.imagekit.io/mLsKqNSuB/post/random/nanaminsr1.jpg",
"04" : "https://ik.imagekit.io/mLsKqNSuB/post/random/mouse1.jpg",
"05" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kyodoki-nanami02.jpg",
"06" : "https://ik.imagekit.io/mLsKqNSuB/post/random/shinigami-02.jpg",
"07" : "https://ik.imagekit.io/mLsKqNSuB/post/random/thegift-02.jpg",
"08" : "https://ik.imagekit.io/mLsKqNSuB/post/random/cinema-addict-nanase-02.jpg",
"09" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kakehashi-cm1-1.png",
"10" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kakehashi-cm2-1.jpg",
"11" : "https://ik.imagekit.io/mLsKqNSuB/post/random/210625-yoda-sakagami-b.jpg",
"12" : "https://ik.imagekit.io/mLsKqNSuB/post/random/211031-hirumae-shibata-b.jpg",
"13" : "doc/blank.png",
"14" : "https://ik.imagekit.io/mLsKqNSuB/post/random/210916-toppafile-b.jpg",
"15" : "doc/blank.png",
"16" : "https://ik.imagekit.io/mLsKqNSuB/post/random/219327-2kisei8nindake-b.jpg",
"17" : "https://ik.imagekit.io/mLsKqNSuB/post/random/190506-life-ikutaerika-b.jpg",
"18" : "https://ik.imagekit.io/mLsKqNSuB/post/random/sonotoki-cupstar1.jpg",
"19" : "https://ik.imagekit.io/mLsKqNSuB/post/random/210410-heyheyneo-skz-b.jpg",
"20" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220514-eigaongaku-b.jpg",
"21" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kakehashi-cm3-1.jpg",
"22" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220715-disneyendoa.jpg",
"23" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220726-seventeen-kubo-shiori1.jpg",
"24" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220728-yoda-yuuki-kanyuu1.jpg",
"25" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220721-uratorechaimashita1.jpg",
"26" : "doc/blank.png",
"27" : "doc/blank.png",
"28" : "https://ik.imagekit.io/mLsKqNSuB/post/random/yonimo2022melody-b.jpg",
"29" : "doc/blank.png",
"30" : "https://ik.imagekit.io/mLsKqNSuB/post/random/221123-petitbrunch-b.jpg",
"31" : "https://ik.imagekit.io/mLsKqNSuB/post/random/221130-petitbrunch-b.jpg",
"32" : "doc/blank.png",
"33" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230418-ayanekikitai-b.jpg",
"34" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230508-petitbrunch-b.jpg",
"35" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230516-petitbrunch-b.jpg",
"36" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230523-petitbrunch-b.jpg",
"37" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230627-bananasand-b.jpg",
"38" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230902-doyounanisuru-b.jpg",
"39" : "https://ik.imagekit.io/mLsKqNSuB/post/random/yonimo2023setorikangaete-b.jpg",
"40" : "doc/blank.png",
"41" : "https://ik.imagekit.io/mLsKqNSuB/post/random/231117-lalalife-yodayuuki-b.jpg",
"42" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240218-zenkokuboroiiyado-b.jpg",
"43" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240223-himubus-b.jpg",
"44" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240416-himutaro-endosakura-b.jpg",
"45" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240103-waraidane-b.jpg",
"46" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240721-sumahoganai-b.jpg",
"47" : "https://ik.imagekit.io/mLsKqNSuB/post/random/241102-anothersky02.jpg",
"48" : "doc/blank.png",
"49" : "https://ik.imagekit.io/mLsKqNSuB/post/random/250102-hodoukyou-bts-b.jpg",
  };
console.log(imageThumbB);

// =======================
// IMAGE THUMBNAIL C
// =======================

const imageThumbC = {
"01" : "https://ik.imagekit.io/mLsKqNSuB/post/random/190308-anothersky03.jpg",
"02" : "https://ik.imagekit.io/mLsKqNSuB/post/sorakibun/sorakibun03.jpg",
"03" : "https://ik.imagekit.io/mLsKqNSuB/post/random/nanaminsr3.jpg",
"04" : "https://ik.imagekit.io/mLsKqNSuB/post/random/mouse3.jpg",
"05" : "doc/blank.png",
"06" : "https://ik.imagekit.io/mLsKqNSuB/post/random/shinigami-03.jpg",
"07" : "https://ik.imagekit.io/mLsKqNSuB/post/random/thegift-03.jpg",
"08" : "https://ik.imagekit.io/mLsKqNSuB/post/random/cinema-addict-nanase-03.jpg",
"09" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kakehashi-cm1-3.png",
"10" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kakehashi-cm2-3.jpg",
"11" : "https://ik.imagekit.io/mLsKqNSuB/post/random/210625-yoda-sakagami-d.jpg",
"12" : "https://ik.imagekit.io/mLsKqNSuB/post/random/211031-hirumae-shibata-c.jpg",
"13" : "doc/blank.png",
"14" : "https://ik.imagekit.io/mLsKqNSuB/post/random/210916-toppafile-c.jpg",
"15" : "doc/blank.png",
"16" : "https://ik.imagekit.io/mLsKqNSuB/post/random/219327-2kisei8nindake-c.jpg",
"17" : "https://ik.imagekit.io/mLsKqNSuB/post/random/190506-life-ikutaerika-c.jpg",
"18" : "https://ik.imagekit.io/mLsKqNSuB/post/random/sonotoki-cupstar3.jpg",
"19" : "https://ik.imagekit.io/mLsKqNSuB/post/random/210410-heyheyneo-skz-c.jpg",
"20" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220514-eigaongaku-c.jpg",
"21" : "https://ik.imagekit.io/mLsKqNSuB/post/random/kakehashi-cm3-3.jpg",
"22" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220715-disneyendoc.jpg",
"23" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220726-seventeen-kubo-shiori3.jpg",
"24" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220728-yoda-yuuki-kanyuu3.jpg",
"25" : "https://ik.imagekit.io/mLsKqNSuB/post/random/220721-uratorechaimashita3.jpg",
"26" : "doc/blank.png",
"27" : "doc/blank.png",
"28" : "https://ik.imagekit.io/mLsKqNSuB/post/random/yonimo2022melody-c.jpg",
"29" : "doc/blank.png",
"30" : "https://ik.imagekit.io/mLsKqNSuB/post/random/221123-petitbrunch-c.jpg",
"31" : "https://ik.imagekit.io/mLsKqNSuB/post/random/221130-petitbrunch-c.jpg",
"32" : "doc/blank.png",
"33" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230418-ayanekikitai-c.jpg",
"34" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230508-petitbrunch-c.jpg",
"35" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230516-petitbrunch-c.jpg",
"36" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230523-petitbrunch-c.jpg",
"37" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230627-bananasand-c.jpg",
"38" : "https://ik.imagekit.io/mLsKqNSuB/post/random/230902-doyounanisuru-c.jpg",
"39" : "https://ik.imagekit.io/mLsKqNSuB/post/random/yonimo2023setorikangaete-c.jpg",
"40" : "doc/blank.png",
"41" : "https://ik.imagekit.io/mLsKqNSuB/post/random/231117-lalalife-yodayuuki-c.jpg",
"42" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240218-zenkokuboroiiyado-c.jpg",
"43" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240223-himubus-c.jpg",
"44" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240416-himutaro-endosakura-c.jpg",
"45" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240103-waraidane-c.jpg",
"46" : "https://ik.imagekit.io/mLsKqNSuB/post/random/240721-sumahoganai-c.jpg",
"47" : "https://ik.imagekit.io/mLsKqNSuB/post/random/241102-anothersky03.jpg",
"48" : "doc/blank.png",
"49" : "https://ik.imagekit.io/mLsKqNSuB/post/random/250102-hodoukyou-bts-c.jpg",
  };
console.log(imageThumbC);

const imageThumbX = {
...imageThumbC,
};
console.log(imageThumbX);


// =======================
// LINK HARDSUB
// =======================

const linkHardsub = {
"01" : "https://lokerwfh.net/WrR2eon",
"02" : "https://lokerwfh.net/ltQkraJQ",
"03" : "https://lokerwfh.net/TRp9",
"04" : "https://lokerwfh.net/RbApzPG",
"05" : "https://lokerwfh.net/VZ3J5xEt",
"06" : "https://lokerwfh.net/XCPnnw",
"07" : "https://lokerwfh.net/TLkUv3",
"08" : "https://lokerwfh.net/ur9jcpGQ",
"09" : "https://lokerwfh.net/NZqP8b",
"10" : "https://lokerwfh.net/Ty0w4",
"11" : "https://lokerwfh.net/AsvN4z",
"12" : "https://lokerwfh.net/JX6dnWQ",
"13" : "https://lokerwfh.net/ja5L",
"14" : "https://lokerwfh.net/9kgyrjlJ",
"15" : "https://lokerwfh.net/c8kikS",
"16" : "https://lokerwfh.net/g7wA",
"17" : "https://lokerwfh.net/jauW5UyR",
"18" : "https://lokerwfh.net/7bzv",
"19" : "https://lokerwfh.net/COTNpT",
"20" : "https://lokerwfh.net/qH5fzDD",
"21" : "https://lokerwfh.net/6Y3Axa",
"22" : "https://lokerwfh.net/XVLV2D7w",
"23" : "https://lokerwfh.net/5aEKCCU",
"24" : "https://lokerwfh.net/yf3VKhs",
"25" : "https://lokerwfh.net/wnMP5E",
"26" : "https://lokerwfh.net/STS48H",
"27" : "https://lokerwfh.net/Sx4k9",
"28" : "https://lokerwfh.net/Xj8us4O",
"29" : "https://lokerwfh.net/z2e6H55",
"30" : "https://lokerwfh.net/DArg",
"31" : "https://lokerwfh.net/gCn3972",
"32" : "https://lokerwfh.net/ibhD1Sg",
"33" : "https://lokerwfh.net/06O9D",
"34" : "https://lokerwfh.net/Tcm8CO",
"35" : "https://lokerwfh.net/J7Lk",
"36" : "https://lokerwfh.net/TqfFH5",
"37" : "https://lokerwfh.net/F039",
"38" : "https://lokerwfh.net/5TZZ",
"39" : "https://lokerwfh.net/bbuwgy",
"40" : "https://drive.google.com/file/d/1pJ6Q1MZIgi_zIAjnFX-JYHCJ8nbmCb0m/view?usp=sharing",
"41" : "https://lokerwfh.net/To2MsksW",
"42" : "https://lokerwfh.net/DMEbfR",
"43" : "https://lokerwfh.net/H9jxX",
"44" : "https://lokerwfh.net/ip17cxD",
"45" : "https://sfl.gl/7iQew",
"46" : "https://sfl.gl/ug6A3",
"47" : "https://sfl.gl/a7IqyMZ",
"48" : "https://drive.google.com/file/d/1OLRlj1yRjjsvN6Z5wM9zytyFyApUAzPA/view?usp=sharing",
"49" : "https://sfl.gl/cHtgaWxN",
  };
console.log(linkHardsub);

// =======================
// LINK TRAKTEER
// =======================

const linkTrakteer = {
"01" : "https://trakteer.id/moefangsubs/showcase/190308-another-sky-saito-asuka-re-sub-wDDzi",
"02" : "https://trakteer.id/moefangsubs/showcase/nogizaka46-suzuki-ayane-no-sora-kibun-hikouki-ni-aitai-NuSdP",
"03" : "https://trakteer.id/moefangsubs/showcase/170217-showroom-hashimoto-nanami-TTZhq",
"04" : "https://trakteer.id/moefangsubs/showcase/180827-natsu-omoide-no-tsukurikata-3w8tT",
"05" : "",
"06" : "",
"07" : "",
"08" : "",
"09" : "",
"10" : "",
"11" : "",
"12" : "",
"13" : "",
"14" : "",
"15" : "",
"16" : "https://trakteer.id/moefangsubs/showcase/210327-abema-hori-miona-graduation-emergency-special-program-only-8-2nd-gen-members-nGO7s",
"17" : "",
"18" : "",
"19" : "",
"20" : "",
"21" : "",
"22" : "",
"23" : "",
"24" : "",
"25" : "",
"26" : "",
"27" : "",
"28" : "",
"29" : "",
"30" : "",
"31" : "",
"32" : "",
"33" : "",
"34" : "",
"35" : "",
"36" : "",
"37" : "https://trakteer.id/moefangsubs/showcase/bananasand-tdCbc",
"38" : "https://trakteer.id/moefangsubs/showcase/230902-doyou-wa-nani-suru-saito-asuka-OnCN6",
"39" : "https://trakteer.id/moefangsubs/showcase/yo-nimo-kimyou-na-monogatari-soumatou-no-setori-wa-kangaeteoite-TaxJN",
"40" : "",
"41" : "https://trakteer.id/moefangsubs/showcase/231117-lalalife-yoda-yuuki-ke-taiwan-dan-makan-gyoza-G0mfi",
"42" : "https://trakteer.id/moefangsubs/showcase/240218-zenkoku-boroii-yado-ioki-mao-x-sugawara-satsuki-cut-Wcqr1",
"43" : "https://trakteer.id/moefangsubs/showcase/240223-himubus-nogizaka46-cut-VEPfD",
"44" : "https://trakteer.id/moefangsubs/showcase/walking-no-himutaro-dqupC",
"45" : "https://trakteer.id/moefangsubs/showcase/240103-waraidane-nogizaka46-cut-Lixth",
"46" : "https://trakteer.id/moefangsubs/showcase/240721-sumaho-ga-nai-toki-dou-shiteita-no-yumiki-nao-ioki-mao-jgX9u",
"47" : "https://trakteer.id/moefangsubs/showcase/241102-another-sky-saito-asuka-sConv",
"48" : "",
"49" : "https://trakteer.id/moefangsubs/showcase/behind-the-scene-hodoukyou-ipeiM",
  };
console.log(linkTrakteer);


// =======================
// FILE PASSWORD
// =======================

const filePassword = {
"01" : "",
"02" : "special100supporter",
"03" : "nanaminshowroom",
"04" : "",
"05" : "",
"06" : "",
"07" : "",
"08" : "",
"09" : "",
"10" : "",
"11" : "",
"12" : "",
"13" : "",
"14" : "",
"15" : "",
"16" : "",
"17" : "",
"18" : "",
"19" : "",
"20" : "",
"21" : "",
"22" : "",
"23" : "",
"24" : "",
"25" : "",
"26" : "",
"27" : "",
"28" : "",
"29" : "",
"30" : "",
"31" : "",
"32" : "",
"33" : "",
"34" : "",
"35" : "",
"36" : "",
"37" : "",
"38" : "",
"39" : "",
"40" : "",
"41" : "",
"42" : "",
"43" : "",
"44" : "",
"45" : "",
"46" : "",
"47" : "",
"48" : "",
"49" : "",
  };
console.log(filePassword);

// =======================
// BAHASA SUB
// =======================

const subLanguage = {};
for (let i = 1; i <= 9999; i++) {
  subLanguage[i.toString().padStart(2, '0')] = "Bahasa Indonesia";
}
console.log(subLanguage);