// database
export const db_saku = [

{ url: "https://files.catbox.moe/9j2nmv.mp3", title: "Overture" },
{ url: "https://files.catbox.moe/a2ihvj.mp3", title: "Masatsukeisuu" },
{ url: "https://files.catbox.moe/twj61t.mp3", title: "Joukenhansha de Naketekuru" },
{ url: "https://files.catbox.moe/1j137o.mp3", title: "One-way stairs" },
{ url: "https://files.catbox.moe/vz0i0n.mp3", title: "Time Machine de Yeah!" },
{ url: "https://files.catbox.moe/9sdggj.mp3", title: "Zutto Haru dattara naa" },
{ url: "https://files.catbox.moe/1i3i4s.mp3", title: "Addiction" },
{ url: "https://files.catbox.moe/2ipl72.mp3", title: "Nobody's Fault" },
{ url: "https://files.catbox.moe/cljkdg.mp3", title: "Naze Koi o Shite Konakatta ndarou?" },
{ url: "https://files.catbox.moe/k398kw.mp3", title: "Hanshin Hangi" },
{ url: "https://files.catbox.moe/jjdvz1.mp3", title: "Plastic Regret" },
{ url: "https://files.catbox.moe/kdnr8y.mp3", title: "Saishuu no Chikatetsu ni Notte" },
{ url: "https://files.catbox.moe/e1bfvc.mp3", title: "Buddies" },
{ url: "https://files.catbox.moe/plm4gy.mp3", title: "Blue Moon Kiss" },
{ url: "https://files.catbox.moe/nwdyfd.mp3", title: "BAN" },
{ url: "https://files.catbox.moe/97wjq8.mp3", title: "Guuzen no Kotae" },
{ url: "https://files.catbox.moe/p26qfl.mp3", title: "Sorega Ai na no ne" },
{ url: "https://files.catbox.moe/e0hh1z.mp3", title: "Kimi to Boku to Sentakumono" },
{ url: "https://files.catbox.moe/7h231z.mp3", title: "Microscope" },
{ url: "https://files.catbox.moe/phqb5t.mp3", title: "Omotta yori mo Sabishikunai" },
{ url: "https://files.catbox.moe/bz1zmf.mp3", title: "Sakurazaka no Uta" },
{ url: "https://files.catbox.moe/7bowrp.mp3", title: "Nagaredama" },
{ url: "https://files.catbox.moe/0ec09y.mp3", title: "Dead End" },
{ url: "https://files.catbox.moe/2qhg9a.mp3", title: "Sonia" },
{ url: "https://files.catbox.moe/0q11ro.mp3", title: "Jamaica Beer" },
{ url: "https://files.catbox.moe/guxz8w.mp3", title: "On My Way" },
{ url: "https://files.catbox.moe/eze79i.mp3", title: "Mugon no Uchuu" },
{ url: "https://files.catbox.moe/k1lcyh.mp3", title: "Utsukushiki Nervous" },
{ url: "https://files.catbox.moe/t4zk61.mp3", title: "Samidare yo" },
{ url: "https://files.catbox.moe/jwjcap.mp3", title: "Boku no Dilemma" },
{ url: "https://files.catbox.moe/7ec367.mp3", title: "I'm in" },
{ url: "https://files.catbox.moe/zl2eh4.mp3", title: "Danzetsu" },
{ url: "https://files.catbox.moe/ulc2i4.mp3", title: "Seifuku no Ningyo" },
{ url: "https://files.catbox.moe/hv2gbe.mp3", title: "Shakan Kyori" },
{ url: "https://files.catbox.moe/mjpt9t.mp3", title: "Koi ga Zetsumetsu Suru Hi" },
{ url: "https://files.catbox.moe/704mmm.mp3", title: "Sakurazuki" },
{ url: "https://files.catbox.moe/jfpcu3.mp3", title: "Cool" },
{ url: "https://files.catbox.moe/xekkoi.mp3", title: "Munen" },
{ url: "https://files.catbox.moe/fibck9.mp3", title: "Moshikashitara Shinjitsu" },
{ url: "https://files.catbox.moe/j6a9i7.mp3", title: "Tamashii no Liar" },
{ url: "https://files.catbox.moe/3ol684.mp3", title: "Natsu no Chikamichi" },
{ url: "https://files.catbox.moe/mpy1tx.mp3", title: "Sono Hi Made" },
{ url: "https://files.catbox.moe/8ispuh.mp3", title: "Start Over!" },
{ url: "https://files.catbox.moe/vkvg3u.mp3", title: "Seijaku no Bouryoku" },
{ url: "https://files.catbox.moe/ykgand.mp3", title: "Kaze no Oto" },
{ url: "https://files.catbox.moe/9rmly3.mp3", title: "Kombinat" },
{ url: "https://files.catbox.moe/n261ck.mp3", title: "Anthem Time" },
{ url: "https://files.catbox.moe/zwc8x0.mp3", title: "Isshun no Uma" },
{ url: "https://files.catbox.moe/0mo6av.mp3", title: "Drone Senkaichuu" },
{ url: "https://files.catbox.moe/7lp87q.mp3", title: "Shounin Yokkyuu" },
{ url: "https://files.catbox.moe/ntfm79.mp3", title: "Mamoribito" },
{ url: "https://files.catbox.moe/8iezil.mp3", title: "Kakushinteki Croissant" },
{ url: "https://files.catbox.moe/1ln4vm.mp3", title: "Bokutachi no La Vie En Rose" },
{ url: "https://files.catbox.moe/mmvxpx.mp3", title: "Don’t Cut In Line!" },
{ url: "https://files.catbox.moe/q558lw.mp3", title: "Manhole no Futa no Ue" },
{ url: "https://files.catbox.moe/m0e1od.mp3", title: "Sukimakaze yo" },
{ url: "https://files.catbox.moe/t1eyn7.mp3", title: "Kimi ga Sayonara Ietatte" },
{ url: "https://files.catbox.moe/ke091i.mp3", title: "Ikutsu no Koro ni Modoritainoka" },
{ url: "https://files.catbox.moe/sq4vwo.mp3", title: "Nando Love Song no Kashi o Yomikaeshitadarou" },
{ url: "https://files.catbox.moe/tx4lmt.mp3", title: "Abura o Sase!" },
{ url: "https://files.catbox.moe/untf2x.mp3", title: "Manatsu ni Nan iga Okiru no kashira" },
{ url: "https://files.catbox.moe/57286a.mp3", title: "Kokoro no Kage e" },
{ url: "https://files.catbox.moe/mbd22x.mp3", title: "Koi wa Muitenai" },
{ url: "https://files.catbox.moe/lo9ub8.mp3", title: "Nakasete Hold Me Tight!" },
{ url: "https://files.catbox.moe/9eu48y.mp3", title: "Jigou Jitoku" },
{ url: "https://files.catbox.moe/ce9g69.mp3", title: "Hikikomoru Jikan wa Nai" },
{ url: "https://files.catbox.moe/p2xfp4.mp3", title: "Aishiainasai" },
{ url: "https://files.catbox.moe/nj4kef.mp3", title: "Isabel ni Tuite" },
{ url: "https://files.catbox.moe/ph0ce8.mp3", title: "Engi Katsugi" },
{ url: "https://files.catbox.moe/bhbqtz.mp3", title: "Hyoushiki" },
{ url: "https://files.catbox.moe/f8s9mv.mp3", title: "Mouikkyoku Hoshii no kai?" },
{ url: "https://files.catbox.moe/dru2zs.mp3", title: "I want tomorrow to come" },
{ url: "https://files.catbox.moe/ckwj4o.mp3", title: "Honshitsuteki na Koto" },
{ url: "https://files.catbox.moe/5i9zn7.mp3", title: "Boku wa Boku o Suki ni Narenai" },
{ url: "https://files.catbox.moe/686q84.mp3", title: "Ima sara Suddenly" },
{ url: "https://files.catbox.moe/4h1jq6.mp3", title: "Arashi no Mae, Sekai no Owari" },
{ url: "https://files.catbox.moe/hmrod1.mp3", title: "Juukyuusai no Galette" },
{ url: "https://files.catbox.moe/yytart.mp3", title: "TOKYO SNOW" },
{ url: "https://files.catbox.moe/sqg98a.mp3", title: "UDAGAWA GENERATION" },
{ url: "https://files.catbox.moe/mjdogf.mp3", title: "Nightmare Shoukougun" },
{ url: "https://files.catbox.moe/pe26y6.mp3", title: "Nothing Special" },
{ url: "https://files.catbox.moe/m57lsi.mp3", title: "Monshirochou ga Tashika Tondeta" },
{ url: "https://files.catbox.moe/z9kteb.mp3", title: "Ikanai de" },
{ url: "https://files.catbox.moe/j42net.mp3", title: "ULTRAVIOLET" },
{ url: "https://files.catbox.moe/h0lfzy.mp3", title: "Yarushikanaijan" },

];